# zedBSD lightweight desktop taskbar
# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
include $(dir $(lastword $(MAKEFILE_LIST)))../../base/package.mk

$(eval $(call ZEDBSD_USERLAND_PACKAGE,zshell,zshell,*,n,basic,userland/x11/zshell/main.c userland/x11/libX11/xlib.c,y,x11-applications,,))
