/*
 * WS031 Linux-parity — the device-owned VBT state: what the rest of the parity
 * driver sees of the VBT.  zedBSD project code.
 *
 * The parsing itself is the Linux 6.8.12 reference text (intel_bios_port.c,
 * generated by plan/ws031/handover/tools/port_intel_bios.py).  This layer owns
 * the memory, selects the byte source, and flattens the reference's private
 * lists into plain records the display code can read without Linux types.
 */
#ifndef PARITY_VBT_H
#define PARITY_VBT_H

#include <stdint.h>
#include <stddef.h>

/* Where the VBT bytes came from.  An explicit blob is NOT an OpRegion. */
enum parity_vbt_origin {
	PARITY_VBT_ORIGIN_NONE = 0,       /* no VBT: init_vbt_missing_defaults() */
	PARITY_VBT_ORIGIN_OPREGION,       /* ASLS -> mailbox 4 / RVDA (native path) */
	PARITY_VBT_ORIGIN_PCI_ROM,        /* $VBT in the PCI expansion ROM */
	PARITY_VBT_ORIGIN_EXPLICIT_BLOB,  /* a named, hash-pinned blob supplied by the test configuration */
};

#define PARITY_VBT_MAX_ENCODERS 12
struct parity_vbt_encoder {
	int port;                 /* enum port value (0 = A, 3 = TC1 ...), -1 if none */
	int aux_ch;               /* enum aux_ch value, -1 if none */
	uint16_t device_type;
	uint8_t dvo_port;
	uint8_t ddc_pin_raw;      /* child.ddc_pin as in the VBT */
	int ddc_pin;              /* mapped GMBUS pin (0 = none/invalid) */
	int supports_dp, supports_edp, supports_hdmi, supports_dvi;
	int supports_typec_usb, supports_tbt;
	int lane_reversal, hpd_invert;
	int dp_max_lane_count;    /* 0 = not limited by the VBT */
	int dp_max_link_rate;     /* kHz-per-lane /10 as in the reference (e.g. 270000), 0 = platform max */
	int dp_boost_level, hdmi_boost_level;
	int hdmi_level_shift;     /* -1 = not set */
};

struct parity_vbt_panel {
	int initialized;
	int panel_type;
	int bpp;                          /* eDP colour depth from the VBT: 18 / 24 / 30 */
	int edp_rate;                     /* DP_LINK_BW_* code the VBT names for fast link */
	int edp_lanes;
	int edp_preemphasis, edp_vswing;
	int edp_low_vswing;
	int edp_max_link_rate;            /* 0 = not limited */
	/* eDP panel power sequencing, in 100 us units as stored in the VBT */
	uint16_t t1_t3, t8, t9, t10, t11_t12;
	/* backlight */
	int bl_present;
	int bl_type;                      /* enum intel_backlight_type */
	int bl_controller;
	int bl_active_low_pwm;
	uint16_t bl_pwm_freq_hz;
	uint8_t bl_min_brightness;
	/* the VBT's own panel mode, if it carries one (the EDID mode normally wins) */
	int has_lfp_mode;
	int mode_clock_khz;
	uint16_t hdisplay, hsync_start, hsync_end, htotal;
	uint16_t vdisplay, vsync_start, vsync_end, vtotal;
	int drrs_type, vrr;
};

struct parity_vbt {
	int inited;
	int origin;                       /* enum parity_vbt_origin */
	const uint8_t *bytes;             /* the validated VBT (not owned) */
	size_t size;
	uint16_t bdb_version;
	char signature[21];
	int missing_defaults_used;
	unsigned num_bdb_blocks;
	unsigned n_encoders;
	struct parity_vbt_encoder enc[PARITY_VBT_MAX_ENCODERS];
	/* general features the display code consumes */
	int int_lvds_support, display_clock_mode, lvds_use_ssc, lvds_ssc_freq, crt_ddc_pin;
	unsigned arena_used, arena_peak, alloc_failures;
	unsigned log_errors;              /* drm_err / WARN lines the reference emitted */
};

/*
 * intel_bios_init() on the given bytes (NULL/0 = no VBT -> missing defaults).
 * The bytes must already be validated by parity_vbt_validate().  Returns 0, or
 * -EBUSY when a VBT state is already live (one device).
 */
int parity_vbt_init(struct parity_vbt *v, const void *bytes, size_t size, int origin);
/* intel_bios_is_valid_vbt(): 1 when the header, BDB offset and BDB size fit in `size`. */
int parity_vbt_validate(const void *bytes, size_t size);
/*
 * intel_bios_init_panel_late() for the encoder on `port`, with the panel's EDID
 * (128 bytes, may be NULL -> the reference's fallback panel type).  Fills *out.
 */
int parity_vbt_init_panel(struct parity_vbt *v, int port, const uint8_t *edid128,
	struct parity_vbt_panel *out);
const struct parity_vbt_encoder *parity_vbt_encoder_for_port(const struct parity_vbt *v, int port);
/* intel_bios_driver_remove(): releases every list and the arena. */
void parity_vbt_fini(struct parity_vbt *v);

/* verbosity of the reference's drm_dbg_kms lines: 0 errors only, 1 +info, 2 +debug */
void parity_vbt_set_log_level(int level);

#endif /* PARITY_VBT_H */
