/*
 * zedBSD
 * Copyright (C) 2026 Awe Morris
 */

/*
 * SPDX-License-Identifier: MIT
 *
 * Copyright © 2003-2018 Intel Corporation
 * Copyright © 2019 Intel Corporation
 */

/*
 * The GPU commands the driver quotes from the Linux i915 headers: the MI
 * command opcodes and their flags, the blitter commands, PIPE_CONTROL and its
 * flags, and the invalidate and flush selectors of a flush emission.
 *
 * The GPU commands (Linux v6.19 intel_gpu_commands.h, generated by gen-inc.py).
 * Modified for zedBSD: excerpted, mechanically rewritten and reformatted from the
 * Linux kernel tag v6.19. Values are unchanged. Sources (SHA-256 of the fetched file):
 *   drivers/gpu/drm/i915/gt/intel_gpu_commands.h
 *     d8d14b3edefb858418eb52506f5f7598ee2cd6bd8affa659e43faaf11c85e77c
 * Rewrites: _MMIO(x) -> (x); REG_BIT/BIT -> I915_INC_BIT; REG_BIT64/BIT_ULL -> I915_INC_BIT64;
 * REG_GENMASK/GENMASK -> I915_INC_GENMASK; GENMASK_ULL -> I915_INC_GENMASK64; PAGE_SIZE ->
 * I915_INC_PAGE_SIZE; integer shift bases gain a U suffix; variadic MACRO__ tables drop their
 * __VA_ARGS__ pass-through; sizeof(u32)/sizeof(u64) -> 4U/8U; BUILD_BUG_ON_ZERO terms are removed.
 * Only the subset used by src/drivers/gpu/i915 remains.
 * Generated by gen-inc.py, now retired (plan/ws031/handover/tools/retired/).
 *
 * The commands of the execution path (Linux 6.8.12).
 * Modified for zedBSD: excerpted by hand from the Linux kernel 6.8.12, the
 * version the execution path was ported from and tested against.  Values are
 * unchanged.  Sources:
 *   drivers/gpu/drm/i915/gt/intel_gpu_commands.h
 *   drivers/gpu/drm/i915/gt/intel_engine_types.h
 * Rewrites: _MMIO(x) -> (x); REG_BIT/BIT -> I915_INC_BIT; REG_GENMASK ->
 * I915_INC_GENMASK; PAGE_SIZE -> I915_INC_PAGE_SIZE; sizeof(u32)/sizeof(u64) ->
 * 4U/8U; integer shift bases gain a U suffix.
 * Only what the execution path uses and the v6.19 extract above does not
 * already hold is here; it builds on that extract's definitions.  The
 * registers of the same excerpt are in gt-regs.h.
 */

#ifndef DRIVERS_GPU_I915_INTEL_COMMANDS_H
#define DRIVERS_GPU_I915_INTEL_COMMANDS_H

#include "bits.h"

/* The GPU commands (Linux v6.19 intel_gpu_commands.h, generated by gen-inc.py). */

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:21 */
#define INSTR_CLIENT_SHIFT	29

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:22 */
#define INSTR_MI_CLIENT	0x0

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:23 */
#define INSTR_BC_CLIENT	0x2

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:25 */

#define INSTR_RC_CLIENT	0x3

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:32 */
#define __INSTR(client)	((client) << INSTR_CLIENT_SHIFT)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:37 */
#define MI_INSTR(opcode, flags)	(__INSTR(INSTR_MI_CLIENT) | (opcode) << 23 | (flags))

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:42 */
#define MI_NOOP	MI_INSTR(0, 0)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:45 */
#define MI_USER_INTERRUPT	MI_INSTR(0x02, 0)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:384 */
#define MI_ARB_CHECK	MI_INSTR(0x05, 0)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:59 */
#define MI_ARB_ON_OFF	MI_INSTR(0x08, 0)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:60 */
#define MI_ARB_ENABLE	(1U << 0)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:61 */
#define MI_ARB_DISABLE	(0U << 0)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:62 */
#define MI_BATCH_BUFFER_END	MI_INSTR(0x0a, 0)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:122 */
#define MI_SEMAPHORE_WAIT	MI_INSTR(0x1c, 2) /* GEN8+ */

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:123 */
#define MI_SEMAPHORE_WAIT_TOKEN	MI_INSTR(0x1c, 3) /* GEN12+ */

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:125 */
#define MI_SEMAPHORE_POLL	(1U << 15)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:130 */
#define MI_SEMAPHORE_SAD_EQ_SDD	(4U << 12)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:127 */
#define MI_SEMAPHORE_SAD_GTE_SDD	(1U << 12)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:93 */
#define MI_SEMAPHORE_GLOBAL_GTT	(1U << 22)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:136 */
#define MI_STORE_DWORD_IMM_GEN4	MI_INSTR(0x20, 2)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:139 */
#define MI_USE_GGTT	(1U << 22) /* g4x+ */

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:138 */
#define MI_MEM_VIRTUAL	(1U << 22) /* 945,g33,965 */

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:155 */
#define MI_LOAD_REGISTER_IMM(x)	MI_INSTR(0x22, 2*(x)-1)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:159 */
#define MI_LRI_FORCE_POSTED	(1U << 12)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:157 */
#define MI_LRI_LRM_CS_MMIO	I915_INC_BIT(19)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:158 */
#define MI_LRI_MMIO_REMAP_EN	I915_INC_BIT(17)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:162 */
#define MI_STORE_REGISTER_MEM_GEN8	MI_INSTR(0x24, 2)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:163 */
#define MI_SRM_LRM_GLOBAL_GTT	(1U << 22)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:164 */
#define MI_FLUSH_DW	MI_INSTR(0x26, 1) /* for GEN6 */

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:166 */
#define MI_FLUSH_DW_STORE_INDEX	(1U << 21)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:169 */
#define MI_FLUSH_DW_OP_STOREDW	(1U << 14)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:174 */
#define MI_FLUSH_DW_USE_GTT	(1U << 2)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:167 */
#define MI_INVALIDATE_TLB	(1U << 18)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:188 */
#define MI_BATCH_BUFFER_START_GEN8	MI_INSTR(0x31, 1)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:183 */
#define MI_BATCH_NON_SECURE_I965	(1U << 8)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:270 */
#define XY_SRC_COPY_BLT_CMD	(2U << 29 | 0x53 << 22)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:240 */
#define XY_COLOR_BLT_CMD	(2U << 29 | 0x50 << 22)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:274 */
#define BLT_WRITE_RGBA	(BLT_WRITE_RGB | BLT_WRITE_A)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:273 */
#define BLT_WRITE_RGB	(1U << 20)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:272 */
#define BLT_WRITE_A	(2U << 20)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:278 */
#define BLT_DEPTH_32	(3U << 24)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:279 */
#define BLT_ROP_SRC_COPY	(0xcc<<16)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:280 */
#define BLT_ROP_COLOR_COPY	(0xf0<<16)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:281 */
#define XY_SRC_COPY_BLT_SRC_TILED	(1U << 15) /* 965+ only */

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:282 */
#define XY_SRC_COPY_BLT_DST_TILED	(1U << 11) /* 965+ only */

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:287 */
#define GFX_OP_PIPE_CONTROL(len)	((0x3<<29)|(0x3<<27)|(0x2<<24)|((len)-2))

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:295 */
#define PIPE_CONTROL_CS_STALL	(1U << 20)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:301 */
#define PIPE_CONTROL_QW_WRITE	(1U << 14)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:292 */
#define PIPE_CONTROL_GLOBAL_GTT_IVB	(1U << 24) /* gen7+ */

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:312 */
#define PIPE_CONTROL_FLUSH_ENABLE	(1U << 7) /* gen7+ */

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:297 */
#define PIPE_CONTROL_TLB_INVALIDATE	(1U << 18)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:306 */
#define PIPE_CONTROL_RENDER_TARGET_CACHE_FLUSH	(1U << 12) /* gen6+ */

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:318 */
#define PIPE_CONTROL_DEPTH_CACHE_FLUSH	(1U << 0)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:313 */
#define PIPE_CONTROL_DC_FLUSH_ENABLE	(1U << 5)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:289 */
#define PIPE_CONTROL_TILE_CACHE_FLUSH	(1U << 28) /* gen11+ */

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:290 */
#define PIPE_CONTROL_FLUSH_L3	(1U << 27)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:303 */
#define PIPE_CONTROL_DEPTH_STALL	(1U << 13)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:294 */
#define PIPE_CONTROL_STORE_DATA_INDEX	(1U << 21)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:310 */
#define PIPE_CONTROL0_HDC_PIPELINE_FLUSH	I915_INC_BIT(9) /* gen12 */

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:288 */
#define PIPE_CONTROL_COMMAND_CACHE_INVALIDATE	(1U << 29) /* gen11+ */

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:307 */
#define PIPE_CONTROL_INSTRUCTION_CACHE_INVALIDATE	(1U << 11) /* MBZ on ILK */

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:308 */
#define PIPE_CONTROL_TEXTURE_CACHE_INVALIDATE	(1U << 10) /* GM45+ only */

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:314 */
#define PIPE_CONTROL_VF_CACHE_INVALIDATE	(1U << 4)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:315 */
#define PIPE_CONTROL_CONST_CACHE_INVALIDATE	(1U << 3)

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h:316 */
#define PIPE_CONTROL_STATE_CACHE_INVALIDATE	(1U << 2)

/* The commands of the execution path (Linux 6.8.12). */

/* drivers/gpu/drm/i915/gt/intel_gpu_commands.h */
#define MI_SET_PREDICATE	MI_INSTR(0x01, 0)
#define MI_SET_PREDICATE_DISABLE	(0U << 0)
#define MI_SEMAPHORE_REGISTER_POLL	(1U << 16)
#define MI_LOAD_REGISTER_MEM_GEN8	MI_INSTR(0x29, 2)
#define MI_LOAD_REGISTER_REG	MI_INSTR(0x2A, 1)
#define MI_LRR_SOURCE_CS_MMIO	I915_INC_BIT(18)
#define MI_FLUSH_DW_CCS	(1U << 16)
#define MI_INVALIDATE_BSD	(1U << 7)

/* drivers/gpu/drm/i915/gt/intel_engine_types.h */
#define EMIT_INVALIDATE	I915_INC_BIT(0)
#define EMIT_FLUSH	I915_INC_BIT(1)
#define EMIT_BARRIER	(EMIT_INVALIDATE | EMIT_FLUSH)

#endif /* DRIVERS_GPU_I915_INTEL_COMMANDS_H */
