/*
 * zedBSD
 * Copyright (C) 2026 Awe Morris
 */

/*
 * Copyright © 2019 Intel Corporation
 * Copyright © 2022 Intel Corporation
 * Copyright 2003 Tungsten Graphics, Inc., Cedar Park, Texas.
 * Copyright © 2014-2018 Intel Corporation
 * Copyright © 2014 Intel Corporation
 * Copyright © 2016 Intel Corporation
 * Copyright © 2020 Intel Corporation
 * Copyright(c) 2023, Intel Corporation. All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sub license, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice (including the
 * next paragraph) shall be included in all copies or substantial portions
 * of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.
 * IN NO EVENT SHALL TUNGSTEN GRAPHICS AND/OR ITS SUPPLIERS BE LIABLE FOR
 * ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/*
 * The GT registers and fields the driver quotes from the Linux i915 headers:
 * the engine classes, the PCI BARs and the GMCH control word, forcewake,
 * reset, the ring, execlist and context-control registers of an engine, the
 * GT interrupt registers, the hardware status page slots, the logical ring
 * context layout and descriptor fields, and the GTT page-table entry bits.
 *
 * The GT, engine, interrupt, context and GTT registers (Linux v6.19, generated by gen-inc.py).
 * Modified for zedBSD: excerpted, mechanically rewritten and reformatted from the
 * Linux kernel tag v6.19. Values are unchanged. Sources (SHA-256 of the fetched file):
 *   drivers/gpu/drm/i915/gt/intel_engine_types.h
 *     47b77f01148818361cf0f0c02bb40fd6420b06941d6e06516e9447f3146b6a62
 *   drivers/gpu/drm/i915/intel_pci_config.h
 *     f792fd35a880fc179a4d556b78125466e8ff0668f7aaaa7957c286bc8fbdd462
 *   include/drm/intel/i915_drm.h
 *     46a108e9401fd36f2405db8f70f84dddeca8ddc76fc2a33b53a0d53608c0e82e
 *   drivers/gpu/drm/i915/gt/intel_gt_regs.h
 *     2d131eb5839396c099e8c63b52e8f998407936d8a34df4a547080fc13f5a91b9
 *   drivers/gpu/drm/i915/gt/intel_engine_regs.h
 *     e6ae20bc2946a252a948628df6a84522c19dd45d537f5efa0e5c55d08e82961a
 *   drivers/gpu/drm/i915/i915_reg.h
 *     756e332354a4be1eb62edea220127c632eadb8ebdbe83c558d158476395ce0f0
 *   drivers/gpu/drm/i915/gt/intel_lrc_reg.h
 *     671b2adfb2825597425eea515b892cba1365f658d552f9a90439182f0f7f21c0
 *   drivers/gpu/drm/i915/gt/intel_lrc.h
 *     e71534746b6f6720c978c0096316c51873f5afc2974d94cd4979303384a6f5b3
 *   drivers/gpu/drm/i915/gt/intel_engine_cs.c
 *     aacc2f24da117cdb95b61d12933540701558504317269ad62028aafd1205db48
 *   drivers/gpu/drm/i915/gt/intel_execlists_submission.c
 *     f017c05d94d69d03506204610d108190a4e78b0a2ee8ee9267e4438a95adc3fd
 *   drivers/gpu/drm/i915/gt/intel_engine.h
 *     d07100bbdd00a2874b19851134c56b56c448df0219be67acb01e89ab3ed996cc
 *   drivers/gpu/drm/i915/gt/intel_gtt.h
 *     f3b92ef5fc03006fea2f84f50e6c7f0a05096b82846e18329cb2a81fa4a411b0
 * Rewrites: _MMIO(x) -> (x); REG_BIT/BIT -> I915_INC_BIT; REG_BIT64/BIT_ULL -> I915_INC_BIT64;
 * REG_GENMASK/GENMASK -> I915_INC_GENMASK; GENMASK_ULL -> I915_INC_GENMASK64; PAGE_SIZE ->
 * I915_INC_PAGE_SIZE; integer shift bases gain a U suffix; variadic MACRO__ tables drop their
 * __VA_ARGS__ pass-through; sizeof(u32)/sizeof(u64) -> 4U/8U; BUILD_BUG_ON_ZERO terms are removed.
 * Only the subset used by src/drivers/gpu/i915 remains.
 * Generated by gen-inc.py, now retired (plan/ws031/handover/tools/retired/).
 * The MOCS registers of this extract (BLIT_CCTL and its fields,
 * GEN12_GLOBAL_MOCS, GEN9_LNCFCMOCS) are in mocs.h.
 *
 * The engine registers and context definitions of the execution path (Linux 6.8.12).
 * Modified for zedBSD: excerpted by hand from the Linux kernel 6.8.12, the
 * version the execution path was ported from and tested against.  Values are
 * unchanged.  Sources:
 *   drivers/gpu/drm/i915/gt/intel_engine.h
 *   drivers/gpu/drm/i915/gt/intel_engine_regs.h
 *   drivers/gpu/drm/i915/gt/intel_gt_regs.h
 *   drivers/gpu/drm/i915/gt/intel_lrc.h
 *   drivers/gpu/drm/i915/gt/intel_lrc.c
 *   drivers/gpu/drm/i915/gt/intel_lrc_reg.h
 *   drivers/gpu/drm/i915/pxp/intel_pxp_regs.h
 * Rewrites: _MMIO(x) -> (x); REG_BIT/BIT -> I915_INC_BIT; REG_GENMASK ->
 * I915_INC_GENMASK; PAGE_SIZE -> I915_INC_PAGE_SIZE; sizeof(u32)/sizeof(u64) ->
 * 4U/8U; integer shift bases gain a U suffix.
 * Only what the execution path uses and the v6.19 extract above does not
 * already hold is here; it builds on that extract's definitions.  The commands
 * of the same excerpt are in commands.h.
 */

#ifndef DRIVERS_GPU_I915_INTEL_GT_REGS_H
#define DRIVERS_GPU_I915_INTEL_GT_REGS_H

#include "bits.h"

/* The GT, engine, interrupt, context and GTT registers (Linux v6.19, generated by gen-inc.py). */

/* drivers/gpu/drm/i915/gt/intel_engine_types.h:31 */
#define RENDER_CLASS	0

/* drivers/gpu/drm/i915/gt/intel_engine_types.h:34 */
#define COPY_ENGINE_CLASS	3

/* drivers/gpu/drm/i915/gt/intel_engine_types.h:32 */
#define VIDEO_DECODE_CLASS	1

/* drivers/gpu/drm/i915/gt/intel_engine_types.h:33 */
#define VIDEO_ENHANCEMENT_CLASS	2

/* drivers/gpu/drm/i915/gt/intel_engine_types.h:35 */
#define OTHER_CLASS	4

/* drivers/gpu/drm/i915/intel_pci_config.h:19 */
#define GEN4_GTTMMADR_BAR	0 /* MMIO+GTT */

/* drivers/gpu/drm/i915/intel_pci_config.h:20 */
#define GEN4_GMADR_BAR	2

/* include/drm/intel/i915_drm.h:49 */
#define SNB_GMCH_CTRL	0x50

/* include/drm/intel/i915_drm.h:54 */
#define BDW_GMCH_GGMS_SHIFT	6

/* include/drm/intel/i915_drm.h:55 */
#define BDW_GMCH_GGMS_MASK	0x3

/* drivers/gpu/drm/i915/gt/intel_gt_regs.h:864 */
#define FORCEWAKE_GT_GEN9	(0xa188)

/* drivers/gpu/drm/i915/gt/intel_gt_regs.h:1496 */
#define FORCEWAKE_ACK_GT_GEN9	(0x130044)

/* drivers/gpu/drm/i915/gt/intel_gt_regs.h:910 */
#define FORCEWAKE_RENDER_GEN9	(0xa278)

/* drivers/gpu/drm/i915/gt/intel_gt_regs.h:56 */
#define FORCEWAKE_ACK_RENDER_GEN9	(0xd84)

/* drivers/gpu/drm/i915/gt/intel_gt_regs.h:921 */
#define FORCEWAKE_MEDIA_VDBOX_GEN11(n)	(0xa540 + (n) * 4)

/* drivers/gpu/drm/i915/gt/intel_gt_regs.h:54 */
#define FORCEWAKE_ACK_MEDIA_VDBOX_GEN11(n)	(0xd50 + (n) * 4)

/* drivers/gpu/drm/i915/gt/intel_gt_regs.h:922 */
#define FORCEWAKE_MEDIA_VEBOX_GEN11(n)	(0xa560 + (n) * 4)

/* drivers/gpu/drm/i915/gt/intel_gt_regs.h:55 */
#define FORCEWAKE_ACK_MEDIA_VEBOX_GEN11(n)	(0xd70 + (n) * 4)

/* drivers/gpu/drm/i915/gt/intel_gt_regs.h:1497 */
#define FORCEWAKE_KERNEL	I915_INC_BIT(0)

/* drivers/gpu/drm/i915/gt/intel_gt_regs.h:1474 */
#define GFX_FLSH_CNTL_GEN6	(0x101008)

/* drivers/gpu/drm/i915/gt/intel_gt_regs.h:1475 */
#define GFX_FLSH_CNTL_EN	(1U << 0)

/* drivers/gpu/drm/i915/gt/intel_gt_regs.h:663 */
#define GEN6_GDRST	(0x941c)

/* drivers/gpu/drm/i915/gt/intel_gt_regs.h:664 */
#define GEN6_GRDOM_FULL	(1U << 0)

/* drivers/gpu/drm/i915/gt/intel_gt_regs.h:665 */
#define GEN6_GRDOM_RENDER	(1U << 1)

/* drivers/gpu/drm/i915/gt/intel_gt_regs.h:673 */
#define GEN11_GRDOM_RENDER	GEN6_GRDOM_RENDER

/* drivers/gpu/drm/i915/gt/intel_gt_regs.h:700 */
#define GEN11_GRDOM_BLT	I915_INC_BIT(2)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:103 */
#define RING_RESET_CTL(base)	((base) + 0xd0)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:106 */
#define RESET_CTL_REQUEST_RESET	I915_INC_BIT(0)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:105 */
#define RESET_CTL_READY_TO_RESET	I915_INC_BIT(1)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:104 */
#define RESET_CTL_CAT_ERROR	I915_INC_BIT(2)

/* drivers/gpu/drm/i915/i915_reg.h:243 */
#define RENDER_RING_BASE	0x02000

/* drivers/gpu/drm/i915/i915_reg.h:265 */
#define BLT_RING_BASE	0x22000

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:12 */
#define RING_TAIL(base)	((base) + 0x30)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:14 */
#define RING_HEAD(base)	((base) + 0x34)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:17 */
#define HEAD_ADDR	0x001FFFFC

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:13 */
#define TAIL_ADDR	0x001FFFF8

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:19 */
#define RING_START(base)	((base) + 0x38)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:20 */
#define RING_CTL(base)	((base) + 0x3c)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:21 */
#define RING_CTL_SIZE(size)	((size) - I915_INC_PAGE_SIZE) /* in bytes -> pages */

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:28 */
#define RING_VALID	0x00000001

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:66 */
#define RING_HWS_PGA(base)	((base) + 0x80)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:72 */
#define RING_HWSTAM(base)	((base) + 0x98)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:73 */
#define RING_MI_MODE(base)	((base) + 0x9c)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:78 */
#define STOP_RING	I915_INC_BIT(8)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:77 */
#define MODE_IDLE	I915_INC_BIT(9)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:80 */
#define RING_IMR(base)	((base) + 0xa8)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:81 */
#define RING_EIR(base)	((base) + 0xb0)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:82 */
#define RING_EMR(base)	((base) + 0xb4)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:83 */
#define RING_ESR(base)	((base) + 0xb8)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:65 */
#define RING_ACTHD(base)	((base) + 0x74)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:58 */
#define RING_ACTHD_UDW(base)	((base) + 0x5c)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:113 */
#define RING_BBADDR(base)	((base) + 0x140)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:115 */
#define RING_BBADDR_UDW(base)	((base) + 0x168) /* gen8+ */

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:60 */
#define RING_IPEIR(base)	((base) + 0x64)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:61 */
#define RING_IPEHR(base)	((base) + 0x68)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:62 */
#define RING_INSTDONE(base)	((base) + 0x6c)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:181 */
#define RING_CONTEXT_CONTROL(base)	((base) + 0x244)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:185 */
#define CTX_CTRL_INHIBIT_SYN_CTX_SWITCH	I915_INC_BIT(3)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:182 */
#define CTX_CTRL_ENGINE_CTX_RESTORE_INHIBIT	I915_INC_BIT(0)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:190 */
#define GEN8_RING_PDP_UDW(base, n)	((base) + 0x270 + (n) * 8 + 4)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:191 */
#define GEN8_RING_PDP_LDW(base, n)	((base) + 0x270 + (n) * 8)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:192 */
#define RING_MODE_GEN7(base)	((base) + 0x29c)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:193 */
#define GFX_RUN_LIST_ENABLE	(1U << 15)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:206 */
#define GEN11_GFX_DISABLE_LEGACY_MODE	(1U << 3)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:199 */
#define GEN12_GFX_PREFETCH_DISABLE	I915_INC_BIT(10)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:178 */
#define RING_ELSP(base)	((base) + 0x230)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:179 */
#define RING_EXECLIST_STATUS_LO(base)	((base) + 0x234)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:180 */
#define RING_EXECLIST_STATUS_HI(base)	((base) + 0x234 + 4)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:209 */
#define RING_CONTEXT_STATUS_PTR(base)	((base) + 0x3a0)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:232 */
#define RING_EXECLIST_SQ_CONTENTS(base)	((base) + 0x510)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:234 */
#define RING_EXECLIST_CONTROL(base)	((base) + 0x550)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:235 */
#define EL_CTRL_LOAD	I915_INC_BIT(0)

/* drivers/gpu/drm/i915/gt/intel_lrc_reg.h:53 */
#define GEN8_EXECLISTS_STATUS_BUF	0x370

/* drivers/gpu/drm/i915/gt/intel_lrc_reg.h:54 */
#define GEN11_EXECLISTS_STATUS_BUF2	0x3c0

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:120 */
#define RING_BB_PER_CTX_PTR(base)	((base) + 0x1c0) /* gen8+ */

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:124 */
#define RING_INDIRECT_CTX(base)	((base) + 0x1c4) /* gen8+ */

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:125 */
#define RING_INDIRECT_CTX_OFFSET(base)	((base) + 0x1c8) /* gen8+ */

/* drivers/gpu/drm/i915/i915_reg.h:914 */
#define GEN11_GFX_MSTR_IRQ	(0x190010)

/* drivers/gpu/drm/i915/i915_reg.h:915 */
#define GEN11_MASTER_IRQ	(1U << 31)

/* drivers/gpu/drm/i915/i915_reg.h:918 */
#define GEN11_DISPLAY_IRQ	(1U << 16)

/* drivers/gpu/drm/i915/i915_reg.h:917 */
#define GEN11_GU_MISC_IRQ	(1U << 29)

/* drivers/gpu/drm/i915/i915_reg.h:919 */
#define GEN11_GT_DW_IRQ(x)	(1U << (x))

/* drivers/gpu/drm/i915/gt/intel_gt_regs.h:1558 */
#define GEN11_GT_INTR_DW(x)	(0x190018 + ((x) * 4))

/* drivers/gpu/drm/i915/gt/intel_gt_regs.h:1594 */
#define GEN11_INTR_IDENTITY_REG(x)	(0x190060 + ((x) * 4))

/* drivers/gpu/drm/i915/gt/intel_gt_regs.h:1595 */
#define GEN11_INTR_DATA_VALID	(1U << 31)

/* drivers/gpu/drm/i915/gt/intel_gt_regs.h:1596 */
#define GEN11_INTR_ENGINE_CLASS(x)	(((x) & I915_INC_GENMASK(18, 16)) >> 16)

/* drivers/gpu/drm/i915/gt/intel_gt_regs.h:1597 */
#define GEN11_INTR_ENGINE_INSTANCE(x)	(((x) & I915_INC_GENMASK(25, 20)) >> 20)

/* drivers/gpu/drm/i915/gt/intel_gt_regs.h:1598 */
#define GEN11_INTR_ENGINE_INTR(x)	((x) & 0xffff)

/* drivers/gpu/drm/i915/gt/intel_gt_regs.h:1608 */
#define GEN11_IIR_REG_SELECTOR(x)	(0x190070 + ((x) * 4))

/* drivers/gpu/drm/i915/gt/intel_gt_regs.h:1584 */
#define GEN11_RENDER_COPY_INTR_ENABLE	(0x190030)

/* drivers/gpu/drm/i915/gt/intel_gt_regs.h:1585 */
#define GEN11_VCS_VECS_INTR_ENABLE	(0x190034)

/* drivers/gpu/drm/i915/gt/intel_gt_regs.h:1610 */
#define GEN11_RCS0_RSVD_INTR_MASK	(0x190090)

/* drivers/gpu/drm/i915/gt/intel_gt_regs.h:1611 */
#define GEN11_BCS_RSVD_INTR_MASK	(0x1900a0)

/* drivers/gpu/drm/i915/gt/intel_gt_regs.h:1612 */
#define GEN11_VCS0_VCS1_INTR_MASK	(0x1900a8)

/* drivers/gpu/drm/i915/gt/intel_gt_regs.h:1613 */
#define GEN11_VCS2_VCS3_INTR_MASK	(0x1900ac)

/* drivers/gpu/drm/i915/gt/intel_gt_regs.h:1616 */
#define GEN11_VECS0_VECS1_INTR_MASK	(0x1900d0)

/* drivers/gpu/drm/i915/gt/intel_gt_regs.h:1589 */
#define GEN11_GPM_WGBOXPERF_INTR_ENABLE	(0x19003c)

/* drivers/gpu/drm/i915/gt/intel_gt_regs.h:1621 */
#define GEN11_GPM_WGBOXPERF_INTR_MASK	(0x1900ec)

/* drivers/gpu/drm/i915/gt/intel_gt_regs.h:1586 */
#define GEN11_GUC_SG_INTR_ENABLE	(0x190038)

/* drivers/gpu/drm/i915/gt/intel_gt_regs.h:1619 */
#define GEN11_GUC_SG_INTR_MASK	(0x1900e8)

/* drivers/gpu/drm/i915/gt/intel_gt_regs.h:1590 */
#define GEN11_CRYPTO_RSVD_INTR_ENABLE	(0x190040)

/* drivers/gpu/drm/i915/gt/intel_gt_regs.h:1622 */
#define GEN11_CRYPTO_RSVD_INTR_MASK	(0x1900f0)

/* drivers/gpu/drm/i915/i915_reg.h:515 */
#define GT_RENDER_USER_INTERRUPT	(1U <<  0)

/* drivers/gpu/drm/i915/i915_reg.h:509 */
#define GT_CONTEXT_SWITCH_INTERRUPT	(1U <<  8)

/* drivers/gpu/drm/i915/i915_reg.h:512 */
#define GT_CS_MASTER_ERROR_INTERRUPT	I915_INC_BIT(3)

/* drivers/gpu/drm/i915/i915_reg.h:508 */
#define GT_WAIT_SEMAPHORE_INTERRUPT	I915_INC_BIT(11) /* bdw+ */

/* drivers/gpu/drm/i915/i915_reg.h:396 */
#define I915_ERROR_INSTRUCTION	(1U << 0)

/* drivers/gpu/drm/i915/gt/intel_lrc.h:23 */
#define LRC_PPHWSP_PN	(0)

/* drivers/gpu/drm/i915/gt/intel_lrc.h:24 */
#define LRC_PPHWSP_SZ	(1)

/* drivers/gpu/drm/i915/gt/intel_lrc.h:26 */
#define LRC_STATE_PN	(LRC_PPHWSP_PN + LRC_PPHWSP_SZ)

/* drivers/gpu/drm/i915/gt/intel_lrc.h:27 */
#define LRC_STATE_OFFSET	(LRC_STATE_PN * I915_INC_PAGE_SIZE)

/* drivers/gpu/drm/i915/gt/intel_lrc.h:30 */
#define LRC_PPHWSP_SCRATCH	0x34

/* drivers/gpu/drm/i915/gt/intel_lrc.h:31 */
#define LRC_PPHWSP_SCRATCH_ADDR	(LRC_PPHWSP_SCRATCH * 4U)

/* drivers/gpu/drm/i915/gt/intel_engine_cs.c:48 */
#define GEN11_LR_CONTEXT_RENDER_SIZE	(14 * I915_INC_PAGE_SIZE)

/* drivers/gpu/drm/i915/gt/intel_engine_cs.c:50 */
#define GEN8_LR_CONTEXT_OTHER_SIZE	(2 * I915_INC_PAGE_SIZE)

/* drivers/gpu/drm/i915/gt/intel_lrc_reg.h:14 */
#define CTX_CONTEXT_CONTROL	(0x02 + 1)

/* drivers/gpu/drm/i915/gt/intel_lrc_reg.h:15 */
#define CTX_RING_HEAD	(0x04 + 1)

/* drivers/gpu/drm/i915/gt/intel_lrc_reg.h:16 */
#define CTX_RING_TAIL	(0x06 + 1)

/* drivers/gpu/drm/i915/gt/intel_lrc_reg.h:17 */
#define CTX_RING_START	(0x08 + 1)

/* drivers/gpu/drm/i915/gt/intel_lrc_reg.h:18 */
#define CTX_RING_CTL	(0x0a + 1)

/* drivers/gpu/drm/i915/gt/intel_lrc_reg.h:19 */
#define CTX_BB_STATE	(0x10 + 1)

/* drivers/gpu/drm/i915/gt/intel_lrc_reg.h:20 */
#define CTX_TIMESTAMP	(0x22 + 1)

/* drivers/gpu/drm/i915/gt/intel_lrc_reg.h:27 */
#define CTX_PDP0_UDW	(0x30 + 1)

/* drivers/gpu/drm/i915/gt/intel_lrc_reg.h:28 */
#define CTX_PDP0_LDW	(0x32 + 1)

/* drivers/gpu/drm/i915/gt/intel_lrc_reg.h:29 */
#define CTX_R_PWR_CLK_STATE	(0x42 + 1)

/* drivers/gpu/drm/i915/gt/intel_lrc.h:91 */
#define GEN8_CTX_VALID	(1U << 0)

/* drivers/gpu/drm/i915/gt/intel_lrc.h:93 */
#define GEN8_CTX_FORCE_RESTORE	(1U << 2)

/* drivers/gpu/drm/i915/gt/intel_lrc.h:94 */
#define GEN8_CTX_L3LLC_COHERENT	(1U << 5)

/* drivers/gpu/drm/i915/gt/intel_lrc.h:95 */
#define GEN8_CTX_PRIVILEGE	(1U << 8)

/* drivers/gpu/drm/i915/gt/intel_lrc.h:96 */
#define GEN8_CTX_ADDRESSING_MODE_SHIFT	3

/* drivers/gpu/drm/i915/gt/intel_lrc.h:101 */
#define GEN8_CTX_ID_SHIFT	32

/* drivers/gpu/drm/i915/gt/intel_lrc.h:103 */
#define GEN11_SW_CTX_ID_SHIFT	37

/* drivers/gpu/drm/i915/gt/intel_lrc.h:104 */
#define GEN11_SW_CTX_ID_WIDTH	11

/* drivers/gpu/drm/i915/gt/intel_lrc.h:105 */
#define GEN11_ENGINE_CLASS_SHIFT	61

/* drivers/gpu/drm/i915/gt/intel_lrc.h:107 */
#define GEN11_ENGINE_INSTANCE_SHIFT	48

/* drivers/gpu/drm/i915/gt/intel_lrc_reg.h:75 */
#define GEN11_MAX_CONTEXT_HW_ID	(1U << 11) /* exclusive */

/* drivers/gpu/drm/i915/gt/intel_lrc_reg.h:77 */
#define GEN12_MAX_CONTEXT_HW_ID	(GEN11_MAX_CONTEXT_HW_ID - 1)

/* drivers/gpu/drm/i915/gt/intel_execlists_submission.c:163 */
#define GEN12_IDLE_CTX_ID	0x7FF

/* drivers/gpu/drm/i915/gt/intel_lrc_reg.h:11 */
#define CTX_DESC_FORCE_RESTORE	I915_INC_BIT64(2)

/* drivers/gpu/drm/i915/gt/intel_lrc_reg.h:69 */
#define GEN11_CSB_ENTRIES	12

/* drivers/gpu/drm/i915/gt/intel_engine.h:201 */
#define I915_HWS_CSB_BUF0_INDEX	0x10

/* drivers/gpu/drm/i915/gt/intel_engine.h:203 */
#define ICL_HWS_CSB_WRITE_INDEX	0x2f

/* drivers/gpu/drm/i915/gt/intel_engine.h:188 */
#define I915_GEM_HWS_PREEMPT	0x32

/* drivers/gpu/drm/i915/gt/intel_engine.h:190 */
#define I915_GEM_HWS_SEQNO	0x40

/* drivers/gpu/drm/i915/gt/intel_engine.h:191 */
#define I915_GEM_HWS_SEQNO_ADDR	(I915_GEM_HWS_SEQNO * 4U)

/* drivers/gpu/drm/i915/gt/intel_engine.h:199 */
#define I915_GEM_HWS_SCRATCH	0x80

/* drivers/gpu/drm/i915/gt/intel_execlists_submission.c:160 */
#define GEN12_CTX_STATUS_SWITCHED_TO_NEW_QUEUE	(0x1) /* lower csb dword */

/* drivers/gpu/drm/i915/gt/intel_execlists_submission.c:161 */
#define GEN12_CTX_SWITCH_DETAIL(csb_dw)	((csb_dw) & 0xF) /* upper csb dword */

/* drivers/gpu/drm/i915/gt/intel_execlists_submission.c:162 */
#define GEN12_CSB_SW_CTX_ID_MASK	I915_INC_GENMASK(25, 15)

/* drivers/gpu/drm/i915/gt/intel_engine_types.h:234 */
#define EXECLIST_MAX_PORTS	2

/* drivers/gpu/drm/i915/gt/intel_gtt.h:45 */
#define I915_GTT_PAGE_SIZE_4K	I915_INC_BIT64(12)

/* drivers/gpu/drm/i915/gt/intel_gtt.h:68 */
#define I915_PDES	512

/* drivers/gpu/drm/i915/gt/intel_gtt.h:69 */
#define I915_PDE_MASK	(I915_PDES - 1)

/* drivers/gpu/drm/i915/gt/intel_gtt.h:133 */
#define GEN8_3LVL_PDPES	4

/* drivers/gpu/drm/i915/gt/intel_gtt.h:152 */
#define GEN8_PAGE_PRESENT	I915_INC_BIT64(0)

/* drivers/gpu/drm/i915/gt/intel_gtt.h:153 */
#define GEN8_PAGE_RW	I915_INC_BIT64(1)

/* drivers/gpu/drm/i915/gt/intel_gtt.h:95 */
#define GEN12_PPGTT_PTE_PAT0	I915_INC_BIT64(3)

/* drivers/gpu/drm/i915/gt/intel_gtt.h:94 */
#define GEN12_PPGTT_PTE_PAT1	I915_INC_BIT64(4)

/* drivers/gpu/drm/i915/gt/intel_gtt.h:93 */
#define GEN12_PPGTT_PTE_PAT2	I915_INC_BIT64(7)

/* drivers/gpu/drm/i915/gt/intel_gtt.h:97 */
#define GEN12_GGTT_PTE_LM	I915_INC_BIT64(1)

/* drivers/gpu/drm/i915/gt/intel_gtt.h:100 */
#define GEN12_GGTT_PTE_ADDR_MASK	I915_INC_GENMASK64(45, 12)

/* drivers/gpu/drm/i915/gt/intel_gtt.h:156 */
#define GEN8_PDE_PS_2M	I915_INC_BIT(7)

/* drivers/gpu/drm/i915/gt/intel_gtt.h:155 */
#define GEN8_PDE_IPS_64K	I915_INC_BIT(11)

/* The engine registers and context definitions of the execution path (Linux 6.8.12). */

/* drivers/gpu/drm/i915/gt/intel_engine.h */
#define I915_GEM_HWS_PREEMPT_ADDR	(I915_GEM_HWS_PREEMPT * 4U)
#define I915_GEM_HWS_MIGRATE	(0x42 * 4U)
#define I915_GEM_HWS_PXP	0x60
#define I915_GEM_HWS_PXP_ADDR	(I915_GEM_HWS_PXP * 4U)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h */
#define RING_CMD_BUF_CCTL(base)	((base) + 0x84)
#define RING_CTX_TIMESTAMP(base)	((base) + 0x3a8) /* gen8+ */
#define GEN8_RING_CS_GPR(base, n)	((base) + 0x600 + (n) * 8)

/* drivers/gpu/drm/i915/gt/intel_gt_regs.h */
#define GEN12_CS_DEBUG_MODE2	(0x20d8)
#define INSTRUCTION_STATE_CACHE_INVALIDATE	I915_INC_BIT(6)
#define GEN12_CCS_AUX_INV	(0x4208)
#define GEN12_VD0_AUX_INV	(0x4218)
#define GEN12_VE0_AUX_INV	(0x4238)
#define GEN12_BCS0_AUX_INV	(0x4248)
#define GEN12_VD2_AUX_INV	(0x4298)
#define AUX_INV	I915_INC_BIT(0)
#define MSG_IDLE_CS	(0x8000)
#define MSG_IDLE_VCS0	(0x8004)
#define MSG_IDLE_BCS	(0x800C)
#define MSG_IDLE_VECS0	(0x8010)
#define MSG_IDLE_VCS2	(0x80C0)
#define MSG_IDLE_FW_MASK	I915_INC_GENMASK(13, 9)
#define MSG_IDLE_FW_SHIFT	9
#define GEN9_PWRGT_DOMAIN_STATUS	(0xA2A0)
#define GEN8_RPCS_ENABLE	(1U << 31)
#define GEN8_RPCS_S_CNT_ENABLE	(1U << 18)
#define GEN11_RPCS_S_CNT_SHIFT	12
#define GEN11_RPCS_S_CNT_MASK	(0x3fU << GEN11_RPCS_S_CNT_SHIFT)

/* drivers/gpu/drm/i915/gt/intel_lrc.h (enum value) */
#define INTEL_LEGACY_64B_CONTEXT	3

/* drivers/gpu/drm/i915/gt/intel_lrc.c */
#define DG2_PREDICATE_RESULT_WA	(I915_INC_PAGE_SIZE - 8U)
#define DG2_PREDICATE_RESULT_BB	(2048)

/* drivers/gpu/drm/i915/gt/intel_lrc_reg.h */
#define GEN12_CTX_RCS_INDIRECT_CTX_OFFSET_DEFAULT	0xD

/* drivers/gpu/drm/i915/pxp/intel_pxp_regs.h */
#define GEN12_KCR_BASE	0x32000

#endif /* DRIVERS_GPU_I915_INTEL_GT_REGS_H */
