/*
 * zedBSD
 * Copyright (C) 2026 Awe Morris
 */

/*
 * SPDX-License-Identifier: MIT
 *
 * Copyright © 2014 Intel Corporation
 */

/*
 * The Gen12 logical ring context image offset tables of Linux intel_lrc.c:
 * for the copy engine and for the render engine, the registers the hardware
 * saves in a context image, in the order it writes them.  Each table is a
 * static constant array, so every file that includes this header has its own
 * copy of the tables it uses.
 *
 * The Gen12 context image offset tables (Linux v6.19 intel_lrc.c, generated by gen-inc.py).
 * Modified for zedBSD: excerpted, mechanically rewritten and reformatted from the
 * Linux kernel tag v6.19. Values are unchanged. Sources (SHA-256 of the fetched file):
 *   drivers/gpu/drm/i915/gt/intel_lrc.c
 *     76817c337bbf7292de60b6050b963bc938aaac33e12a390058af0874c88eef5b
 * Rewrites: _MMIO(x) -> (x); REG_BIT/BIT -> I915_INC_BIT; REG_BIT64/BIT_ULL -> I915_INC_BIT64;
 * REG_GENMASK/GENMASK -> I915_INC_GENMASK; GENMASK_ULL -> I915_INC_GENMASK64; PAGE_SIZE ->
 * I915_INC_PAGE_SIZE; integer shift bases gain a U suffix; variadic MACRO__ tables drop their
 * __VA_ARGS__ pass-through; sizeof(u32)/sizeof(u64) -> 4U/8U; BUILD_BUG_ON_ZERO terms are removed.
 * File-specific renames: NOP( -> I915_LRC_NOP(; LRI( -> I915_LRC_LRI(; POSTED -> I915_LRC_POSTED; REG16( -> I915_LRC_REG16(; REG( -> I915_LRC_REG(; END -> I915_LRC_END; static const u8 -> static const uint8_t.
 * Only the subset used by src/drivers/gpu/i915 remains.
 * Generated by gen-inc.py, now retired (plan/ws031/handover/tools/retired/).
 */

#ifndef DRIVERS_GPU_I915_INTEL_LRC_OFFSETS_H
#define DRIVERS_GPU_I915_INTEL_LRC_OFFSETS_H

#include <stdint.h>

#include "bits.h"

/* drivers/gpu/drm/i915/gt/intel_lrc.c:53-60 */
#define I915_LRC_NOP(x) (I915_INC_BIT(7) | (x))
#define I915_LRC_LRI(count, flags) ((flags) << 6 | (count))
#define I915_LRC_POSTED I915_INC_BIT(0)
#define I915_LRC_REG(x) (((x) >> 2))
#define I915_LRC_REG16(x) \
	(((x) >> 9) | I915_INC_BIT(7)), \
	(((x) >> 2) & 0x7f)
#define I915_LRC_END 0

/* drivers/gpu/drm/i915/gt/intel_lrc.c:227-257 */
static const uint8_t gen12_xcs_offsets[] = {
	I915_LRC_NOP(1),
	I915_LRC_LRI(13, I915_LRC_POSTED),
	I915_LRC_REG16(0x244),
	I915_LRC_REG(0x034),
	I915_LRC_REG(0x030),
	I915_LRC_REG(0x038),
	I915_LRC_REG(0x03c),
	I915_LRC_REG(0x168),
	I915_LRC_REG(0x140),
	I915_LRC_REG(0x110),
	I915_LRC_REG(0x1c0),
	I915_LRC_REG(0x1c4),
	I915_LRC_REG(0x1c8),
	I915_LRC_REG(0x180),
	I915_LRC_REG16(0x2b4),

	I915_LRC_NOP(5),
	I915_LRC_LRI(9, I915_LRC_POSTED),
	I915_LRC_REG16(0x3a8),
	I915_LRC_REG16(0x28c),
	I915_LRC_REG16(0x288),
	I915_LRC_REG16(0x284),
	I915_LRC_REG16(0x280),
	I915_LRC_REG16(0x27c),
	I915_LRC_REG16(0x278),
	I915_LRC_REG16(0x274),
	I915_LRC_REG16(0x270),

	I915_LRC_END
};

/* drivers/gpu/drm/i915/gt/intel_lrc.c:455-549 */
static const uint8_t gen12_rcs_offsets[] = {
	I915_LRC_NOP(1),
	I915_LRC_LRI(13, I915_LRC_POSTED),
	I915_LRC_REG16(0x244),
	I915_LRC_REG(0x034),
	I915_LRC_REG(0x030),
	I915_LRC_REG(0x038),
	I915_LRC_REG(0x03c),
	I915_LRC_REG(0x168),
	I915_LRC_REG(0x140),
	I915_LRC_REG(0x110),
	I915_LRC_REG(0x1c0),
	I915_LRC_REG(0x1c4),
	I915_LRC_REG(0x1c8),
	I915_LRC_REG(0x180),
	I915_LRC_REG16(0x2b4),

	I915_LRC_NOP(5),
	I915_LRC_LRI(9, I915_LRC_POSTED),
	I915_LRC_REG16(0x3a8),
	I915_LRC_REG16(0x28c),
	I915_LRC_REG16(0x288),
	I915_LRC_REG16(0x284),
	I915_LRC_REG16(0x280),
	I915_LRC_REG16(0x27c),
	I915_LRC_REG16(0x278),
	I915_LRC_REG16(0x274),
	I915_LRC_REG16(0x270),

	I915_LRC_LRI(3, I915_LRC_POSTED),
	I915_LRC_REG(0x1b0),
	I915_LRC_REG16(0x5a8),
	I915_LRC_REG16(0x5ac),

	I915_LRC_NOP(6),
	I915_LRC_LRI(1, 0),
	I915_LRC_REG(0x0c8),
	I915_LRC_NOP(3 + 9 + 1),

	I915_LRC_LRI(51, I915_LRC_POSTED),
	I915_LRC_REG16(0x588),
	I915_LRC_REG16(0x588),
	I915_LRC_REG16(0x588),
	I915_LRC_REG16(0x588),
	I915_LRC_REG16(0x588),
	I915_LRC_REG16(0x588),
	I915_LRC_REG(0x028),
	I915_LRC_REG(0x09c),
	I915_LRC_REG(0x0c0),
	I915_LRC_REG(0x178),
	I915_LRC_REG(0x17c),
	I915_LRC_REG16(0x358),
	I915_LRC_REG(0x170),
	I915_LRC_REG(0x150),
	I915_LRC_REG(0x154),
	I915_LRC_REG(0x158),
	I915_LRC_REG16(0x41c),
	I915_LRC_REG16(0x600),
	I915_LRC_REG16(0x604),
	I915_LRC_REG16(0x608),
	I915_LRC_REG16(0x60c),
	I915_LRC_REG16(0x610),
	I915_LRC_REG16(0x614),
	I915_LRC_REG16(0x618),
	I915_LRC_REG16(0x61c),
	I915_LRC_REG16(0x620),
	I915_LRC_REG16(0x624),
	I915_LRC_REG16(0x628),
	I915_LRC_REG16(0x62c),
	I915_LRC_REG16(0x630),
	I915_LRC_REG16(0x634),
	I915_LRC_REG16(0x638),
	I915_LRC_REG16(0x63c),
	I915_LRC_REG16(0x640),
	I915_LRC_REG16(0x644),
	I915_LRC_REG16(0x648),
	I915_LRC_REG16(0x64c),
	I915_LRC_REG16(0x650),
	I915_LRC_REG16(0x654),
	I915_LRC_REG16(0x658),
	I915_LRC_REG16(0x65c),
	I915_LRC_REG16(0x660),
	I915_LRC_REG16(0x664),
	I915_LRC_REG16(0x668),
	I915_LRC_REG16(0x66c),
	I915_LRC_REG16(0x670),
	I915_LRC_REG16(0x674),
	I915_LRC_REG16(0x678),
	I915_LRC_REG16(0x67c),
	I915_LRC_REG(0x068),
	I915_LRC_REG(0x084),
	I915_LRC_NOP(1),

	I915_LRC_END
};

#endif /* DRIVERS_GPU_I915_INTEL_LRC_OFFSETS_H */
