/*
 * zedBSD
 * Copyright (C) 2026 Awe Morris
 */

/*
 * SPDX-License-Identifier: MIT
 *
 * Copyright © 2022 Intel Corporation
 * Copyright © 2015 Intel Corporation
 * Copyright © 2020 Intel Corporation
 */

/*
 * The cache-control definitions the driver quotes from the Linux i915
 * headers: the MOCS registers of the command streamer, the copy engine, the
 * global table and the L3 cache control pairs, the fields of one MOCS entry
 * and of one L3 cache control half-word, and the Gen12 private PAT and its
 * memory types.  The rows of the Gen12 MOCS table are in mocs-table.inc.
 *
 * The MOCS registers (Linux v6.19, generated by gen-inc.py).
 * Modified for zedBSD: excerpted, mechanically rewritten and reformatted from the
 * Linux kernel tag v6.19. Values are unchanged. Sources (SHA-256 of the fetched file):
 *   drivers/gpu/drm/i915/gt/intel_gt_regs.h
 *     2d131eb5839396c099e8c63b52e8f998407936d8a34df4a547080fc13f5a91b9
 *   drivers/gpu/drm/i915/gt/intel_engine_regs.h
 *     e6ae20bc2946a252a948628df6a84522c19dd45d537f5efa0e5c55d08e82961a
 * Rewrites: _MMIO(x) -> (x); REG_BIT/BIT -> I915_INC_BIT; REG_BIT64/BIT_ULL -> I915_INC_BIT64;
 * REG_GENMASK/GENMASK -> I915_INC_GENMASK; GENMASK_ULL -> I915_INC_GENMASK64; PAGE_SIZE ->
 * I915_INC_PAGE_SIZE; integer shift bases gain a U suffix; variadic MACRO__ tables drop their
 * __VA_ARGS__ pass-through; sizeof(u32)/sizeof(u64) -> 4U/8U; BUILD_BUG_ON_ZERO terms are removed.
 * Only the subset used by src/drivers/gpu/i915 remains.
 * Generated by gen-inc.py, now retired (plan/ws031/handover/tools/retired/).
 *
 * The MOCS and PAT registers and values (Linux 6.8.12).
 * Modified for zedBSD: excerpted by hand from the Linux kernel 6.8.12 and
 * reformatted; values are unchanged.  Sources:
 *   drivers/gpu/drm/i915/gt/intel_workarounds.c
 *   drivers/gpu/drm/i915/gt/intel_gt_regs.h
 *   drivers/gpu/drm/i915/gt/intel_engine_regs.h
 *   drivers/gpu/drm/i915/gt/intel_mocs.c
 *   drivers/gpu/drm/i915/gt/intel_gtt.h
 * Rewrites: _MMIO(x) -> (x); REG_BIT/REG_GENMASK/REG_FIELD_PREP are expanded
 * to their constant values; integer constants gain a U suffix.
 * Only the registers and fields the Alder Lake-P MOCS and PAT programming
 * uses remain.  BLIT_CCTL, GEN12_GLOBAL_MOCS and GEN9_LNCFCMOCS are taken
 * from the v6.19 extract above; this excerpt's copies had the same values and
 * are left out.
 */

#ifndef DRIVERS_GPU_I915_INTEL_MOCS_H
#define DRIVERS_GPU_I915_INTEL_MOCS_H

#include <stdint.h>

#include "bits.h"

/* The MOCS registers (Linux v6.19, generated by gen-inc.py). */

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:136 */
#define BLIT_CCTL(base)	((base) + 0x204)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:137 */
#define BLIT_CCTL_DST_MOCS_MASK	I915_INC_GENMASK(14, 8)

/* drivers/gpu/drm/i915/gt/intel_engine_regs.h:138 */
#define BLIT_CCTL_SRC_MOCS_MASK	I915_INC_GENMASK(6, 0)

/* drivers/gpu/drm/i915/gt/intel_gt_regs.h:295 */
#define GEN12_GLOBAL_MOCS(i)	(0x4000 + (i) * 4) /* Global MOCS regs */

/* drivers/gpu/drm/i915/gt/intel_gt_regs.h:960 */
#define GEN9_LNCFCMOCS(i)	(0xb020 + (i) * 4) /* L3 Cache Control */

/* The MOCS and PAT registers and values (Linux 6.8.12). */

/*
 * engine_fake_wa_init: the command streamer's default MOCS.  Both fields
 * take a MOCS value, which is the table index shifted left by one.
 */
#define RING_CMD_CCTL(base)			((base) + 0xc4U)
#define CMD_CCTL_MOCS_MASK			0x00003fffU
#define CMD_CCTL_MOCS_OVERRIDE(write, read) \
	(((((uint32_t)(write) << 1) << 7) & 0x3f80U) | (((uint32_t)(read) << 1) & 0x7fU))

/* gen12_ctx_gt_mocs_init: the copy engine's source and destination MOCS. */
#define BLIT_CCTL_MASK				0x00007f7fU
#define BLIT_CCTL_MOCS(destination, source) \
	(((((uint32_t)(destination) << 1) << 8) & 0x7f00U) | (((uint32_t)(source) << 1) & 0x7fU))

/* intel_mocs.c: the global MOCS table and the L3 cache control pairs. */

/* intel_mocs.c: one MOCS control value (XXX_MOCS_0 - XXX_MOCS_63). */
#define _LE_CACHEABILITY(value)			((uint32_t)(value) << 0)
#define _LE_TGT_CACHE(value)			((uint32_t)(value) << 2)
#define LE_LRUM(value)				((uint32_t)(value) << 4)
#define LE_AOM(value)				((uint32_t)(value) << 6)
#define LE_RSC(value)				((uint32_t)(value) << 7)
#define LE_SCC(value)				((uint32_t)(value) << 8)
#define LE_SCF(value)				((uint32_t)(value) << 14)
#define LE_SSE(value)				((uint32_t)(value) << 17)
#define LE_1_UC					_LE_CACHEABILITY(1)
#define LE_3_WB					_LE_CACHEABILITY(3)
#define LE_TC_1_LLC				_LE_TGT_CACHE(1)

/* intel_mocs.c: one L3 cache control half-word (LNCFMOCS0 - LNCFMOCS31). */
#define _L3_CACHEABILITY(value)			((uint16_t)((value) << 4))
#define L3_1_UC					_L3_CACHEABILITY(1)
#define L3_3_WB					_L3_CACHEABILITY(3)

/* intel_mocs.c: GEN9_NUM_MOCS_ENTRIES, and the Gen12 table's special indices. */
#define GEN9_NUM_MOCS_ENTRIES			64U
#define GEN12_MOCS_UC_INDEX			3U
#define GEN12_MOCS_UNUSED_ENTRIES_INDEX		2U

/* intel_gtt.h: the Gen12 private PAT and its memory types. */
#define GEN12_PAT_INDEX(index)			(0x4800U + (unsigned)(index) * 4U)
#define GEN8_PPAT_WB				(3U << 0)
#define GEN8_PPAT_WT				(2U << 0)
#define GEN8_PPAT_WC				(1U << 0)
#define GEN8_PPAT_UC				(0U << 0)

#endif /* DRIVERS_GPU_I915_INTEL_MOCS_H */
