#!/bin/sh
# ws089: builds the Settings guest image (plan/ws089/tests/config-amd64-settings.mk, ZEDBSD_KEILAND_WALLPAPERS := y:
# the wallpapers Settings offers, generated by the build) with the guest harness's files, the wallpaper and App
# Home's list of the demonstration (plan/ws035/demo/apps.conf).
# ws136-p001 (2026-10-04): the image is a config.mk build plus files of the tree (plan/tools/guest/test-image.sh).
# The fonts come with the compositor's package (userland/desktop/fonts/); the wallpaper is
# userland/desktop/wallpapers/Birch-Lake.png.
#
#   plan/ws089/tests/build-settings-image.sh [BUILD]     (default build/amd64)
#   SETTINGS_CONFIG=plan/ws089/tests/config-amd64-settings-ime.mk plan/ws089/tests/build-settings-image.sh BUILD
#                                                       (another config, such as the one with the input method)
# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
set -eu
cd "$(dirname -- "$0")/../../.."
build=${1:-build/amd64}
exec plan/tools/guest/test-image.sh "${SETTINGS_CONFIG:-plan/ws089/tests/config-amd64-settings.mk}" "$build" \
	--file /usr/share/keiland/wallpaper.png=userland/desktop/wallpapers/Birch-Lake.png \
	--file /etc/keiland/apps.conf=plan/ws035/demo/apps.conf
