#!/usr/bin/env python3
"""WS031 E-123 round 80: HDMI hotplug slice (b) wired in -- the GMBUS unit (intel_gmbus_port.c, generated by round 79),
its glue, the EDID glue of intel_hdmi_set_edid, the model GMBUS, and the HDMI-EDID test (-DPARITY_HDMI_EDID_TEST=1).
Idempotent.  usage: round80.py <repo root> <src dir>"""
import sys, shutil
root = sys.argv[1].rstrip("/") + "/"
src = sys.argv[2].rstrip("/") + "/"
P = root + "src/drivers/gpu/i915/parity/"
L = P + "lcd/"
NL = chr(10)

def rep(s, old, new, done_marker):
    if done_marker in s:
        return s
    assert s.count(old) == 1, old[:100]
    return s.replace(old, new)

for f in ["hpd_compat.h", "parity_hotplug_glue.inc", "parity_ddi_hotplug_glue.inc", "parity_hdmi_detect_glue.inc",
          "parity_gmbus_glue.inc", "parity_hotplug.h", "parity_hpd_test.c", "hpd_ktest.c"]:
    shutil.copyfile(src + f, L + f)

h = open(P + "bios.h").read()
h = rep(h, "#ifndef PARITY_LCDD_TEST" + NL,
        "#ifndef PARITY_HDMI_EDID_TEST" + NL +
        "#define PARITY_HDMI_EDID_TEST 0       /* E-123: the connected HDMI sink's first detection + EDID over GMBUS */" + NL +
        "#endif" + NL + "#ifndef PARITY_LCDD_TEST" + NL, "PARITY_HDMI_EDID_TEST 0")
h = rep(h, "#define PARITY_VBT_EXPLICIT (PARITY_HDMI_HPD_TEST || ",
        "#define PARITY_VBT_EXPLICIT (PARITY_HDMI_EDID_TEST || PARITY_HDMI_HPD_TEST || ", "(PARITY_HDMI_EDID_TEST ||")
open(P + "bios.h", "w").write(h)

c = open(P + "probe.c").read()
c = rep(c, """	if (PARITY_HDMI_HPD_TEST) {""", """	if (PARITY_HDMI_EDID_TEST) {
		if (parity_hpd_started)
			(void)parity_hdmi_edid_test_run(&mmio);
		else
			kern_logf("i915: parity HDMI-EDID verdict: FAIL (the hotplug path did not start)\\n");
	}
	if (PARITY_HDMI_HPD_TEST) {""", "parity_hdmi_edid_test_run(")
open(P + "probe.c", "w").write(c)

mk = root + "platform/amd64/vmunix.mk"
c = open(mk).read()
c = rep(c, "src/drivers/gpu/i915/parity/lcd/intel_hotplug_port.c ",
        "src/drivers/gpu/i915/parity/lcd/intel_hotplug_port.c src/drivers/gpu/i915/parity/lcd/intel_gmbus_port.c ",
        "lcd/intel_gmbus_port.c")
open(mk, "w").write(c)

for t in ["plan/ws031/tests/run-lcd-modeset-host-test.sh", "plan/ws031/tests/run-lcd-host-test.sh"]:
    c = open(root + t).read()
    c = rep(c, "-e hotplug -e ", "-e hotplug -e intel_gmbus_port.c -e ", "-e intel_gmbus_port.c")
    open(root + t, "w").write(c)
print("done")
