#!/usr/bin/env python3
"""WS031: C arrays of the target panel's captured DPCD / EDID for the GPU-free kernel checks.
usage: gen_dp_fixture.py <plan/ws031/display-ref> <out header>"""
import hashlib, os, sys
ref, out = sys.argv[1], sys.argv[2]
NL = chr(10)
items = [("dp_fixture_dpcd_000", "dpcd-drm_dp_aux0-000.bin"), ("dp_fixture_dpcd_100", "dpcd-drm_dp_aux0-100.bin"),
         ("dp_fixture_dpcd_700", "dpcd-drm_dp_aux0-700.bin"), ("dp_fixture_edid", "edid-eDP-1.bin")]
t = ["/*",
     " * zedBSD WS031: generated by plan/ws031/handover/tools/gen_dp_fixture.py from plan/ws031/display-ref/.",
     " * Test input only: DPCD and EDID bytes read from the target machine's panel (Dell Latitude 5330,",
     " * AUO B133HAN) through Linux i915 on 2026-09-18.  Machine / panel data: licence and",
     " * redistribution NOT audited (see plan/ws031/provenance-ledger.md).",
     " */", "#ifndef PARITY_DP_FIXTURE_LATITUDE5330_H", "#define PARITY_DP_FIXTURE_LATITUDE5330_H", "",
     "#include <stdint.h>", ""]
for name, fn in items:
    b = open(os.path.join(ref, fn), "rb").read()
    t.append("/* %s: %d bytes, sha256 %s */" % (fn, len(b), hashlib.sha256(b).hexdigest()))
    t.append("static const uint8_t %s[%d] = {" % (name, len(b)))
    for i in range(0, len(b), 16):
        t.append(chr(9) + " ".join("0x%02x," % x for x in b[i:i + 16]))
    t.append("};")
    t.append("")
t.append("#endif /* PARITY_DP_FIXTURE_LATITUDE5330_H */")
open(out, "w").write(NL.join(t) + NL)
print("generated", out)
