#!/usr/bin/env python3
"""WS031: first-pass inventory for the licence / provenance work.  Facts only:
per file, what header it carries and which upstream it says it follows.  No judgement."""
import os, re, subprocess, sys
root = os.path.expanduser("~/zedBSD")
base = "src/drivers/gpu/i915"
rows = []
for d, _, fs in os.walk(os.path.join(root, base)):
    for f in sorted(fs):
        if not f.endswith((".c", ".h", ".inc", ".S")):
            continue
        p = os.path.join(d, f)
        rel = os.path.relpath(p, root)
        try:
            s = open(p, errors="replace").read()
        except Exception:
            continue
        head = s[:3000]
        spdx = re.search(r"SPDX-License-Identifier:\s*([^\s*]+(?:\s+(?:OR|AND|WITH)\s+[^\s*]+)*)", head)
        copyr = re.findall(r"Copyright[^\n]{0,80}", head)
        says_linux = len(re.findall(r"\b(drivers/gpu/drm|intel_[a-z0-9_]+\.[ch]|i915_[a-z0-9_]+\.[ch]|gt/[a-z0-9_]+\.[ch]|display/[a-z0-9_]+\.[ch])", s))
        says_mesa = len(re.findall(r"\b(Mesa|mesa|genxml|isl_|brw_|blorp|anv|iris)\b", s))
        gen = bool(re.search(r"GENERATED|Generated by|generated from|Do not edit|Do NOT edit", head))
        tracked = subprocess.run(["git", "-C", root, "ls-files", "--error-unmatch", rel],
                                 capture_output=True).returncode == 0
        rows.append((rel, s.count("\n") + 1, spdx.group(1) if spdx else "-", "; ".join(c.strip(" */") for c in copyr[:2]) or "-",
                     says_linux, says_mesa, "yes" if gen else "-", "yes" if tracked else "NEW"))
print("# WS031 licence inventory (first pass, facts only)\n")
print("自動抽出した事実のみ。判断（区分・互換性・配布可否）は含まない。`linux refs`／`mesa refs` は本文中で上流のファイル名や用語に言及している箇所の数で、複製の有無を示すものではない。\n")
print("| file | lines | SPDX | copyright lines in header | linux refs | mesa refs | generated | tracked |")
print("|---|---|---|---|---|---|---|---|")
for r in sorted(rows):
    print("| `%s` | %d | %s | %s | %d | %d | %s | %s |" % r)
n = len(rows)
print("\n%d files, %d lines. SPDX tag present: %d. Copyright line present: %d. Marked generated: %d." % (
    n, sum(r[1] for r in rows), sum(r[2] != "-" for r in rows), sum(r[3] != "-" for r in rows), sum(r[6] == "yes" for r in rows)))
