#!/usr/bin/env python3
# zedBSD
# Copyright (C) 2026 Awe Morris
# SPDX-License-Identifier: Zlib
"""Writes or checks libkeiland's exports.map from its public header (keiland.h; with keiland-ui.h until WS131 p023) (WS131 p012, plan/ws131/design.md section 5.4).

Only the functions the public headers declare leave the library: every
prototype at the top level of the headers below, by name, without a glob, so
that the shared sources' inner names (picture/color-glyph.c and the like) and
the protocol tables stay inside.

    python3 userland/desktop/libkeiland/exports.py            # writes exports.map
    python3 userland/desktop/libkeiland/exports.py --check    # fails when exports.map differs
    python3 userland/desktop/libkeiland/exports.py --list     # prints the names, one a line
"""

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
HEADERS = [
    os.path.join(HERE, "..", "include", "keiland", "keiland.h"),
]
MAP = os.path.join(HERE, "exports.map")

HEAD = """/*
 * zedBSD
 * Copyright (C) 2026 Awe Morris
 *
 * SPDX-License-Identifier: Zlib
 */

/*
 * Only the calls <keiland/keiland.h> declares leave the library.
 * Generated by exports.py from the headers; do not edit.
 */
{
\tglobal:
"""

TAIL = """\tlocal:
\t\t*;
};
"""


def declared(path):
    """Returns the names of the functions a header declares at its top level."""
    with open(path, encoding="utf-8") as stream:
        text = stream.read()

    # Comments, the C++ linkage block's lines and preprocessor lines (with their continuations) are not declarations.
    text = re.sub(r"/\*.*?\*/", " ", text, flags=re.S)
    text = re.sub(r"#\s*ifdef\s+__cplusplus\b.*?#\s*endif", " ", text, flags=re.S)
    text = re.sub(r"//[^\n]*", " ", text)
    text = re.sub(r"^[ \t]*#(?:[^\n]*\\\n)*[^\n]*", " ", text, flags=re.M)

    # The statements at brace depth 0, split at semicolons.
    statements = []
    depth = 0
    current = []
    for character in text:
        if character == "{":
            depth += 1
        elif character == "}":
            depth -= 1
        if depth == 0 and character == ";":
            statements.append("".join(current))
            current = []
            continue
        if depth == 0 and character != "}":
            current.append(character)
    names = []
    for statement in statements:
        statement = " ".join(statement.split())
        if not statement or statement.startswith("typedef") or statement.startswith("extern \"C\""):
            continue

        # A prototype: the name right before the first parenthesis, not a pointer to a function.
        match = re.match(r"^[A-Za-z_][\w\s\*]*?\b([A-Za-z_]\w*)\s*\(", statement)
        if match is None:
            continue
        if re.search(r"\(\s*\*", statement.split(match.group(1), 1)[0] + "("):
            continue
        names.append(match.group(1))
    return names


def main():
    names = []
    for header in HEADERS:
        for name in declared(header):
            if name not in names:
                names.append(name)
    if "--list" in sys.argv:
        print("\n".join(names))
        return 0
    body = HEAD + "".join("\t\t%s;\n" % name for name in names) + TAIL
    if "--check" in sys.argv:
        with open(MAP, encoding="utf-8") as stream:
            if stream.read() != body:
                print("exports.py: %s is not what the headers declare (run exports.py)" % MAP, file=sys.stderr)
                return 1
        return 0
    with open(MAP, "w", encoding="utf-8") as stream:
        stream.write(body)
    return 0


if __name__ == "__main__":
    sys.exit(main())
