# The FreeBSD build of libkeiland.so; the zedBSD build remains in Makefile.
# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
# keiland-linux-sync: skip userland/base/net/* (networkd is zedBSD only)
KEILAND_FREEBSD_KEILAND_SOURCES := userland/desktop/libkeiland/version.c \
	userland/desktop/libkeiland/menu.c \
	userland/desktop/libkeiland/recent.c \
	userland/desktop/libkeiland/titlebar.c \
	userland/desktop/libkeiland/glass.c \
	userland/desktop/libkeiland/motion.c \
	userland/desktop/libkeiland/scroll.c \
	userland/desktop/libkeiland/gesture.c \
	userland/desktop/libkeiland/desktop.c \
	userland/desktop/libkeiland/keyboard-inset.c \
	userland/desktop/libkeiland/edit.c \
	userland/desktop/libkeiland/settings.c \
	userland/desktop/libkeiland/settings-cache.c \
	userland/desktop/libkeiland/settings-app.c \
	userland/desktop/libkeiland/system/system.c \
	userland/desktop/libkeiland/system/system-view.c \
	userland/desktop/libkeiland/system/system-protocol.c \
	userland/desktop/settings-keys/settings-keys.c \
	userland/desktop/libkeiland/system-compat.c \
	userland/desktop/libkeiland/audio-compat.c
$(eval $(call KEILAND_FREEBSD_LIBRARY,keiland,libkeiland.so,$(KEILAND_FREEBSD_KEILAND_SOURCES),libwayland-client.so libkeiland-backend.a,-lm,userland/desktop/libkeiland/exports.map))
