/*
 * zedBSD
 * Copyright (C) 2026 Awe Morris
 *
 * SPDX-License-Identifier: Zlib
 */

/*
 * The constants of the mathematical library.
 *
 * Generated by src/libc/math/gen/gen-tables.py; do not edit.
 */

#ifndef LIBC_MATH_CONSTANTS_H
#define LIBC_MATH_CONSTANTS_H

/* 128 / ln 2: the number of table steps in one unit of x. */
#define LIBM_EXP_INVERSE_STEP 184.6649652337873

/* ln 2 / 128 to 35 bits, so k times it is exact for |k| < 2^18. */
#define LIBM_EXP_STEP_1 0.0054152123482253955

/* The next 53 bits of ln 2 / 128. */
#define LIBM_EXP_STEP_2 -1.0082281460997769e-13

/* The next 53 bits of ln 2 / 128. */
#define LIBM_EXP_STEP_3 2.3681038446414578e-30

/* 1.5 * 2^52: adding and subtracting it rounds a double below 2^51 to an integer. */
#define LIBM_ROUNDING_SHIFTER 6755399441055744.0

/* ln 2 to 42 bits, so e times it is exact for |e| < 2^11. */
#define LIBM_LN2_SPLIT_HIGH 0.6931471805598903

/* The next 53 bits of ln 2. */
#define LIBM_LN2_SPLIT_LOW 5.497923018708371e-14

/* ln 2 as a double-double: the high part. */
#define LIBM_LN2_HIGH 0.6931471805599453

/* ln 2 as a double-double: the low part. */
#define LIBM_LN2_LOW 2.3190468138462996e-17

/* 1 / ln 2 as a double-double: the high part. */
#define LIBM_INVERSE_LN2_HIGH 1.4426950408889634

/* 1 / ln 2 as a double-double: the low part. */
#define LIBM_INVERSE_LN2_LOW 2.0355273740931033e-17

/* 1 / ln 10 as a double-double: the high part. */
#define LIBM_INVERSE_LN10_HIGH 0.4342944819032518

/* 1 / ln 10 as a double-double: the low part. */
#define LIBM_INVERSE_LN10_LOW 1.098319650216765e-17

/* 1/3 as a double-double: the high part. */
#define LIBM_THIRD_HIGH 0.3333333333333333

/* 1/3 as a double-double: the low part. */
#define LIBM_THIRD_LOW 1.850371707708594e-17

/* pi/2 to 33 bits, so k times it is exact for k < 2^20. */
#define LIBM_HALF_PI_1 1.5707963267341256

/* The next 33 bits of pi/2. */
#define LIBM_HALF_PI_2 6.077100506303966e-11

/* The next 33 bits of pi/2. */
#define LIBM_HALF_PI_3 2.0222662487111665e-21

/* The next 53 bits of pi/2. */
#define LIBM_HALF_PI_4 8.4784276603689e-32

/* 2/pi, which counts the quarter turns in x. */
#define LIBM_TWO_OVER_PI 0.6366197723675814

/* pi/2 as a double-double: the high part. */
#define LIBM_HALF_PI_HIGH 1.5707963267948966

/* pi/2 as a double-double: the low part. */
#define LIBM_HALF_PI_LOW 6.123233995736766e-17

/* pi as a double-double: the high part. */
#define LIBM_PI_HIGH 3.141592653589793

/* pi as a double-double: the low part. */
#define LIBM_PI_LOW 1.2246467991473532e-16

/* pi/4 rounded to the nearest double. */
#define LIBM_QUARTER_PI 0.7853981633974483

/* 3pi/4 rounded to the nearest double. */
#define LIBM_THREE_QUARTER_PI 2.356194490192345

#endif
