#!/usr/bin/env python3
# zedBSD
# Copyright (C) 2026 Awe Morris
# SPDX-License-Identifier: Zlib
"""Generates the table of HTML named character references.

  gen-entities.py ENTITIES.JSON OUTPUT.c

ENTITIES.JSON is the WHATWG HTML Standard's list of named character
references (https://html.spec.whatwg.org/entities.json), downloaded and
checked by the build; the list itself is not kept in the source tree.  The
output is a C array sorted by name in byte order, which the tokenizer
searches for the longest name that matches.
"""

import json
import sys


def main():
    source = sys.argv[1]
    output = sys.argv[2]
    with open(source, encoding="utf-8") as stream:
        entities = json.load(stream)

    rows = []
    for name, entry in entities.items():
        # Every name starts with an ampersand, which the table leaves out.
        if not name.startswith("&"):
            raise SystemExit("gen-entities: a name without '&': %r" % name)
        points = entry["codepoints"]
        if len(points) not in (1, 2):
            raise SystemExit("gen-entities: %s has %d code points" % (name, len(points)))
        second = points[1] if len(points) == 2 else 0
        rows.append((name[1:].encode("ascii"), points[0], second))
    rows.sort()

    lines = []
    lines.append("/*")
    lines.append(" * Generated by userland/base/zdesktop-browser/tools/gen-entities.py; do not edit.")
    lines.append(" *")
    lines.append(" * The named character references of the WHATWG HTML Living Standard")
    lines.append(" * (entities.json), (c) WHATWG (Apple, Google, Mozilla, Microsoft),")
    lines.append(" * under the Creative Commons Attribution 4.0 International License.")
    lines.append(" */")
    lines.append("")
    lines.append('#include "html/entities.h"')
    lines.append("")
    lines.append("/* The references, sorted by name in byte order. */")
    lines.append("const struct html_entity html_entities[] = {")
    for name, first, second in rows:
        lines.append('\t{ "%s", 0x%xU, 0x%xU },' % (name.decode("ascii"), first, second))
    lines.append("};")
    lines.append("")
    lines.append("/* How many references the table holds. */")
    lines.append("const size_t html_entity_count = %d;" % len(rows))
    lines.append("")
    with open(output, "w", encoding="ascii") as stream:
        stream.write("\n".join(lines))


if __name__ == "__main__":
    main()
