#!/bin/sh
# Generate the cross-build entry points external packages are given.
# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
#
# An upstream configure script or CMakeLists expects a compiler that links a
# working program from `cc foo.c -o foo`.  zedBSD's own link lines instead pass
# -nostdlib with an explicit crt1.o, place the shared libc as -l:libc.so after
# the objects, and pin the loader, hash style and relocation options.  Those
# cannot all be expressed as a fixed prefix, because some arguments must come
# before the caller's inputs and some after, so the difference is absorbed here
# once and every package uses the result.
#
# usage: gen-cross-toolchain.sh <triple> <llvm-bin> <sysroot> <dynamic-dir> <outdir>
set -eu

test $# -eq 5 || {
	echo "usage: ${0##*/} <triple> <llvm-bin> <sysroot> <dynamic-dir> <outdir>" >&2
	exit 1
}

triple=$1
llvm_bin=$2
sysroot=$3
dynamic=$4
outdir=$5

for directory in "$llvm_bin" "$sysroot"; do
	test -d "$directory" || { echo "${0##*/}: missing directory: $directory" >&2; exit 1; }
done
test -x "$llvm_bin/clang" || { echo "${0##*/}: missing $llvm_bin/clang" >&2; exit 1; }
test -f "$sysroot/usr/lib/crt1.o" || {
	echo "${0##*/}: missing $sysroot/usr/lib/crt1.o" >&2; exit 1; }

bin="$outdir/bin"
mkdir -p "$bin"

# zedBSD's public headers select the user ABI from KERN_USER_ABI_LP64 rather
# than from the compiler's own __LP64__, and the sysroot carries no header that
# defines it.  The repository passes it in its own CPPFLAGS; an upstream build
# system has no way to know that, so the wrapper supplies it as part of the
# target contract.  Getting this wrong is not silent: sys/stat.h asserts the
# size and layout of struct stat for the ABI it thinks it is compiling for.
case $triple in
x86_64-*) abi_flags='-DKERN_USER_ABI_LP64' ;;
*) abi_flags='' ;;
esac


# ------------------------------------------------------------ compiler driver

# $1 = installed name, $2 = clang driver to run
write_compiler() {
	cat > "$bin/$1" <<WRAPPER
#!/bin/sh
# Generated by userland/packages/tools/gen-cross-toolchain.sh.  Do not edit.
#
# The compiler driver knows this target: it links with ld.lld, supplies the
# start file and the loader, and asks for the shared C library, so the link
# line is not rebuilt here.  What is left is what the driver cannot know --
# which target, which sysroot, and where this build tree keeps its shared
# libraries -- together with two properties of the target itself: the macro
# the public headers read to pick the user ABI, and the thread-local storage
# model.  The loader places the startup set in one static area, so an
# executable and the libraries loaded with it may use any model; an object
# that dlopen() brings in later has no place there and can only be reached
# through the general-dynamic form, which is why it is the default here.
set -eu

# Where this build tree keeps its shared libraries is of use only to a link.
# Passed to a compilation the driver says so, and says it in the words
# cmake reads to mean that a flag it was testing is not supported -- so a
# wrapper that always passed them would quietly turn every one of those
# tests into a failure, and the flags they were testing for would be
# dropped.  They are therefore passed only when a link is going to happen.
zedbsd_link_flags="-L'$dynamic' -Wl,-rpath-link,'$dynamic'"
for zedbsd_argument in "\$@"; do
	case "\$zedbsd_argument" in
	-c|-S|-E|-M|-MM)
		zedbsd_link_flags=
		break
		;;
	esac
done

eval "exec '$llvm_bin/$2' \\
	--target='$triple' \\
	--sysroot='$sysroot' \\
	$abi_flags \\
	-ftls-model=global-dynamic \\
	\$zedbsd_link_flags \\
	\"\\\$@\""
WRAPPER
	chmod +x "$bin/$1"
}

write_compiler zedbsd-clang clang
write_compiler zedbsd-clang++ clang++

# ------------------------------------------------------------ binary utilities

# These need no argument rewriting; the names exist so that a build system is
# given one consistent set of tools rather than reaching for the host's.
for tool in ar ranlib nm objcopy objdump readelf strip; do
	cat > "$bin/zedbsd-$tool" <<WRAPPER
#!/bin/sh
# Generated by userland/packages/tools/gen-cross-toolchain.sh.  Do not edit.
exec '$llvm_bin/llvm-$tool' "\$@"
WRAPPER
	chmod +x "$bin/zedbsd-$tool"
done

cat > "$bin/zedbsd-ld" <<WRAPPER
#!/bin/sh
# Generated by userland/packages/tools/gen-cross-toolchain.sh.  Do not edit.
exec '$llvm_bin/ld.lld' "\$@"
WRAPPER
chmod +x "$bin/zedbsd-ld"

# ------------------------------------------------------------ CMake

# CMake looks for Platform/<system>.cmake beside its own modules; giving it one
# here is what makes shared libraries, the soname flag and the rpath rules
# behave for this system instead of falling back to unknown-platform defaults.
mkdir -p "$outdir/cmake/Platform"
cat > "$outdir/cmake/Platform/zedBSD.cmake" <<'PLATFORM'
# zedBSD platform description for CMake.  Generated; do not edit.
#
# UNIX says what kind of system this is.  CMake sets it for the platforms it
# knows; for one it does not, the description has to say so, and projects read
# it to decide which of their own sources apply.
set(UNIX 1)

# Ordinary ELF shared objects, resolved at load time by /lib/ld.so.
set(CMAKE_DL_LIBS "")
set(CMAKE_SHARED_LIBRARY_C_FLAGS "-fPIC")
set(CMAKE_SHARED_LIBRARY_CXX_FLAGS "-fPIC")

# What to pass when a target asks to be position independent.
#
# The two settings above are what cmake uses for the sources of a shared
# library.  These are what it uses for POSITION_INDEPENDENT_CODE, which a
# project sets on a static library whose objects will end up inside a
# shared one.  Without them cmake has nothing to pass, says nothing, and
# the link fails much later with relocations that cannot be used in a
# shared object.
set(CMAKE_C_COMPILE_OPTIONS_PIC "-fPIC")
set(CMAKE_CXX_COMPILE_OPTIONS_PIC "-fPIC")
set(CMAKE_ASM_COMPILE_OPTIONS_PIC "-fPIC")

# There is deliberately no PIE counterpart.  An executable here is loaded at
# a fixed address, so cmake is left with nothing to pass for that, and a
# project asking for it gets an ordinary executable rather than one this
# loader could not place.
set(CMAKE_SHARED_LIBRARY_CREATE_C_FLAGS "-shared")
set(CMAKE_SHARED_LIBRARY_CREATE_CXX_FLAGS "-shared")
set(CMAKE_SHARED_LIBRARY_LINK_C_FLAGS "")
set(CMAKE_SHARED_LIBRARY_LINK_CXX_FLAGS "")
set(CMAKE_SHARED_LIBRARY_SONAME_C_FLAG "-Wl,-soname,")
set(CMAKE_SHARED_LIBRARY_SONAME_CXX_FLAG "-Wl,-soname,")
set(CMAKE_SHARED_LIBRARY_RUNTIME_C_FLAG "")
set(CMAKE_SHARED_LIBRARY_RUNTIME_C_FLAG_SEP "")
set(CMAKE_SHARED_MODULE_CREATE_C_FLAGS "-shared")
set(CMAKE_SHARED_MODULE_CREATE_CXX_FLAGS "-shared")
set(CMAKE_EXECUTABLE_SUFFIX "")
set(CMAKE_STATIC_LIBRARY_PREFIX "lib")
set(CMAKE_STATIC_LIBRARY_SUFFIX ".a")
set(CMAKE_SHARED_LIBRARY_PREFIX "lib")
set(CMAKE_SHARED_LIBRARY_SUFFIX ".so")
set(CMAKE_FIND_LIBRARY_PREFIXES "lib")
set(CMAKE_FIND_LIBRARY_SUFFIXES ".so" ".a")
PLATFORM

cat > "$outdir/zedbsd.cmake" <<CMAKE
# zedBSD cross toolchain file.  Generated; do not edit.
set(CMAKE_SYSTEM_NAME zedBSD)
set(CMAKE_SYSTEM_PROCESSOR ${triple%%-*})
list(PREPEND CMAKE_MODULE_PATH "$outdir/cmake")

set(CMAKE_C_COMPILER "$bin/zedbsd-clang")
set(CMAKE_CXX_COMPILER "$bin/zedbsd-clang++")
set(CMAKE_ASM_COMPILER "$bin/zedbsd-clang")
set(CMAKE_AR "$bin/zedbsd-ar")
set(CMAKE_RANLIB "$bin/zedbsd-ranlib")
set(CMAKE_NM "$bin/zedbsd-nm")
set(CMAKE_OBJCOPY "$bin/zedbsd-objcopy")
set(CMAKE_OBJDUMP "$bin/zedbsd-objdump")
set(CMAKE_STRIP "$bin/zedbsd-strip")
set(CMAKE_LINKER "$bin/zedbsd-ld")

# The wrapper already carries the target and sysroot; naming them again here
# would put the same fact in two places.
set(CMAKE_SYSROOT "$sysroot")
set(CMAKE_FIND_ROOT_PATH "$sysroot")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_SKIP_RPATH TRUE)
CMAKE

# ------------------------------------------------------------ autoconf

# A cross configure cannot run its own test programs, so it asks for the few
# answers it cannot deduce.  Each entry below is a property of this system that
# was checked against the tree, not a guess to make configure quiet.
cat > "$outdir/zedbsd.cache" <<'CACHE'
# zedBSD autoconf cross cache.  Generated; do not edit.
# Byte order and sizes follow the LP64/ILP32 target ABI the sysroot was built
# for; the remaining entries record facilities the zedBSD libc does provide.
ac_cv_func_getpagesize=${ac_cv_func_getpagesize=yes}
ac_cv_func_memmove=${ac_cv_func_memmove=yes}
ac_cv_func_strftime=${ac_cv_func_strftime=yes}
ac_cv_func_setsid=${ac_cv_func_setsid=yes}
ac_cv_func_getaddrinfo=${ac_cv_func_getaddrinfo=yes}
ac_cv_func_openpty=${ac_cv_func_openpty=yes}
ac_cv_func_arc4random=${ac_cv_func_arc4random=yes}
ac_cv_func_getentropy=${ac_cv_func_getentropy=yes}
CACHE

cat > "$outdir/environment.sh" <<ENVIRONMENT
# zedBSD cross build environment.  Generated; do not edit.
CC='$bin/zedbsd-clang'
CXX='$bin/zedbsd-clang++'
LD='$bin/zedbsd-ld'
AR='$bin/zedbsd-ar'
RANLIB='$bin/zedbsd-ranlib'
NM='$bin/zedbsd-nm'
OBJCOPY='$bin/zedbsd-objcopy'
OBJDUMP='$bin/zedbsd-objdump'
STRIP='$bin/zedbsd-strip'
READELF='$bin/zedbsd-readelf'
ZEDBSD_CROSS_TRIPLE='$triple'
ZEDBSD_CROSS_SYSROOT='$sysroot'
ZEDBSD_CROSS_CMAKE_TOOLCHAIN='$outdir/zedbsd.cmake'
ZEDBSD_CROSS_AUTOCONF_CACHE='$outdir/zedbsd.cache'
export CC CXX LD AR RANLIB NM OBJCOPY OBJDUMP STRIP READELF
ENVIRONMENT

echo "cross toolchain: $outdir"
