include $(dir $(lastword $(MAKEFILE_LIST)))../../base/package.mk

# zedBSD Venus diagnostic client
# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
$(eval $(call ZEDBSD_USERLAND_PACKAGE,venus-frame,Venus Vulkan test frame,amd64,y,basic,userland/tests/venus-frame/venus-frame.c userland/tests/venus-frame/client.c,y,tests,,,0755,program,,,bin))
