include $(dir $(lastword $(MAKEFILE_LIST)))../package.mk

# zedBSD userland package
# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
$(eval $(call ZEDBSD_USERLAND_PACKAGE,chgrp,chgrp,*,y,basic,userland/base/chgrp/main.c userland/base/chown/change.c,y,base,,))
