#!/usr/bin/env python3
# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
"""Generates plan/ws029/i915-symbols.md: the symbols p002-p005 transcribe or re-implement, with their
source file and line in the fixed Linux tag. Values are deliberately not written; the .inc files carry them."""
import re
import sys
from pathlib import Path

ROOT = Path.home() / 'zedBSD'
TAG = sys.argv[1] if len(sys.argv) > 1 else 'v6.19'
TREE = ROOT / 'plan/ws029/temp/linux' / TAG
OUT = ROOT / 'plan/ws029/i915-symbols.md'

# (symbol, use in zedBSD, validity/condition on gen12 ADL-P)
GROUPS = [
 ('補助 macro（値の組み立て、`i915-regs.inc` 先頭へ転記）', 'uncore.c / 全体', [
  ('_MASKED_FIELD', 'masked register 書込み（上位 16 bit が mask）', '全 gen 共通'),
  ('_MASKED_BIT_ENABLE', 'MI_MODE/RING_MODE/CONTEXT_CONTROL の bit set', '全 gen 共通'),
  ('_MASKED_BIT_DISABLE', '同 bit clear', '全 gen 共通'),
  ('REG_BIT', 'bit 定義の展開（.inc では数値へ展開して転記）', '全 gen 共通'),
  ('REG_GENMASK', 'mask 定義の展開', '全 gen 共通'),
  ('REG_FIELD_PREP', 'field 値の組み立て', '全 gen 共通'),
  ('REG_FIELD_GET', 'field 値の取り出し（CSB の SW_CTX_ID）', '全 gen 共通'),
  ('MI_INSTR', 'MI command opcode の組み立て', '全 gen 共通'),
 ]),
 ('device ID / PCI 資源（`i915-ids.inc`、i915.c attach）', 'i915.c', [
  ('INTEL_ADLP_IDS', 'ADL-P device ID 表（0x46a8 を含む）', 'ADL-P; 表全体を転記し attach は 0x46a8 実機で検証'),
  ('INTEL_ADLN_IDS', 'ADL-N ID 表（同 adl_p_info）', '同上、未検証機は「未検証」と記す'),
  ('INTEL_RPLP_IDS', 'RPL-P ID 表（同 adl_p_info）', '同上'),
  ('INTEL_RPLU_IDS', 'RPL-U ID 表（同 adl_p_info）', '同上'),
  ('adl_p_info', 'engine mask（RCS0/BCS0/VECS0/VCS0/VCS2）、ppgtt 48 bit、dma 39 bit', 'ADL-P'),
  ('GEN12_FEATURES', 'has_global_mocs、max_pat_index=3', 'gen12'),
  ('GEN4_GTTMMADR_BAR', 'BAR0（MMIO + GGTT PTE）', 'gen4+'),
  ('GEN4_GMADR_BAR', 'BAR2（aperture、本計画では未使用）', 'gen4+'),
  ('SNB_GMCH_CTRL', 'PCI config の GGTT size field', 'gen6+'),
  ('BDW_GMCH_GGMS_SHIFT', 'GGTT size field shift', 'gen8+'),
  ('BDW_GMCH_GGMS_MASK', 'GGTT size field mask', 'gen8+'),
 ]),
 ('forcewake（uncore.c）', 'uncore.c', [
  ('FORCEWAKE_GT_GEN9', 'GT domain request', 'gen9+（gen11+ で MTL 以外は ACK_GT_GEN9）'),
  ('FORCEWAKE_ACK_GT_GEN9', 'GT domain ack', 'gen9+、IP_VER<12.70'),
  ('FORCEWAKE_RENDER_GEN9', 'RENDER domain request', 'gen9+、RCS あり'),
  ('FORCEWAKE_ACK_RENDER_GEN9', 'RENDER domain ack', 'gen9+'),
  ('FORCEWAKE_MEDIA_VDBOX_GEN11', 'VDBOX domain（本計画は取得しない、定義のみ）', 'gen11+'),
  ('FORCEWAKE_ACK_MEDIA_VDBOX_GEN11', '同 ack', 'gen11+'),
  ('FORCEWAKE_MEDIA_VEBOX_GEN11', 'VEBOX domain（定義のみ）', 'gen11+'),
  ('FORCEWAKE_ACK_MEDIA_VEBOX_GEN11', '同 ack', 'gen11+'),
  ('FORCEWAKE_KERNEL', 'request/ack の bit', 'gen6+'),
  ('GFX_FLSH_CNTL_GEN6', 'GGTT 書込み後の flush/invalidate register', 'gen6+; WC map 時のみ Linux は書く。zedBSD は GGTT を UC で map し毎回書く'),
  ('GFX_FLSH_CNTL_EN', '同 enable bit', 'gen6+'),
 ]),
 ('reset（engine.c）', 'engine.c', [
  ('GEN6_GDRST', 'graphics domain reset register', 'gen6+'),
  ('GEN6_GRDOM_FULL', 'full GT reset domain', 'gen6+'),
  ('GEN6_GRDOM_RENDER', 'RCS0 reset domain', 'gen6+'),
  ('GEN11_GRDOM_BLT', 'BCS0 reset domain', 'gen11+'),
  ('RING_RESET_CTL', 'per-engine reset handshake', 'gen8+'),
  ('RESET_CTL_REQUEST_RESET', 'request bit（masked write）', 'gen8+'),
  ('RESET_CTL_READY_TO_RESET', 'ready bit（700 µs 待つ）', 'gen8+'),
  ('RESET_CTL_CAT_ERROR', 'catastrophic error bit', 'gen11+'),
 ]),
 ('engine register（base 相対、`i915-regs.inc`）', 'engine.c / lrc.c', [
  ('RENDER_RING_BASE', 'RCS0 mmio base', '全 gen'),
  ('BLT_RING_BASE', 'BCS0 mmio base', 'gen6+'),
  ('RING_TAIL', 'ring tail', '全 gen'),
  ('RING_HEAD', 'ring head', '全 gen'),
  ('HEAD_ADDR', 'head address mask', '全 gen'),
  ('TAIL_ADDR', 'tail address mask', '全 gen'),
  ('RING_START', 'ring start（GGTT）', '全 gen'),
  ('RING_CTL', 'ring control', '全 gen'),
  ('RING_CTL_SIZE', 'ring size encode（CTX_RING_CTL 用）', '全 gen'),
  ('RING_VALID', 'ring valid bit', '全 gen'),
  ('RING_HWS_PGA', 'HWSP GGTT address', 'gen4+'),
  ('RING_HWSTAM', 'HWSP write mask（~0 で無効化）', 'gen6+'),
  ('RING_MI_MODE', 'MI_MODE（STOP_RING / MODE_IDLE）', 'gen4+'),
  ('STOP_RING', 'stop ring bit（masked）', 'gen4+'),
  ('MODE_IDLE', 'idle 表示 bit', 'gen6+'),
  ('RING_IMR', 'engine interrupt mask（gen11+ では GT の MASK register が主）', 'gen6+'),
  ('RING_EIR', 'engine error IIR', 'gen8+'),
  ('RING_EMR', 'engine error mask', 'gen8+'),
  ('RING_ESR', 'engine error status', 'gen8+'),
  ('RING_ACTHD', 'active head（hang dump）', 'gen4+'),
  ('RING_ACTHD_UDW', 'active head upper', 'gen8+'),
  ('RING_BBADDR', 'batch buffer address（hang dump）', 'gen4+'),
  ('RING_BBADDR_UDW', '同 upper', 'gen8+'),
  ('RING_IPEIR', 'instruction parser error（hang dump）', 'gen4+'),
  ('RING_IPEHR', 'same', 'gen4+'),
  ('RING_INSTDONE', 'instdone（hang dump）', 'gen4+'),
  ('RING_CONTEXT_CONTROL', 'context control（LRC image の CTX_CONTEXT_CONTROL の対象 register）', 'gen8+'),
  ('CTX_CTRL_INHIBIT_SYN_CTX_SWITCH', 'context control bit', 'gen8+'),
  ('CTX_CTRL_ENGINE_CTX_RESTORE_INHIBIT', 'context control bit（初回 restore inhibit）', 'gen8+'),
  ('GEN8_RING_PDP_UDW', 'PDP register（LRC image の CTX_PDP0_UDW の対象）', 'gen8+'),
  ('GEN8_RING_PDP_LDW', 'same', 'gen8+'),
  ('RING_MODE_GEN7', 'ring mode（GFX_RUN_LIST_ENABLE / LEGACY_MODE）', 'gen7+'),
  ('GFX_RUN_LIST_ENABLE', 'execlists 有効 bit（gen8–10；gen11+ は読出し確認のみ）', 'gen8+'),
  ('GEN11_GFX_DISABLE_LEGACY_MODE', 'execlists 有効化 bit（masked enable）', 'gen11+'),
  ('RING_ELSP', 'legacy ELSP（gen11+ は ELSQ を使う、定義のみ）', 'gen8–10'),
  ('RING_EXECLIST_STATUS_LO', 'execlist status lower', 'gen8+'),
  ('RING_EXECLIST_STATUS_HI', 'execlist status upper', 'gen8+'),
  ('RING_CONTEXT_STATUS_PTR', 'CSB read/write pointer', 'gen8+'),
  ('RING_EXECLIST_SQ_CONTENTS', 'ELSQ submit queue（desc lower/upper × port）', 'gen11+'),
  ('RING_EXECLIST_CONTROL', 'ELSQ load trigger', 'gen11+'),
  ('EL_CTRL_LOAD', 'load bit', 'gen11+'),
  ('GEN8_EXECLISTS_STATUS_BUF', 'CSB mmio mirror（HWSP が -1 のままの時の代替読出し）', 'gen8+'),
  ('GEN11_EXECLISTS_STATUS_BUF2', '同 entries 6–11', 'gen11+'),
  ('BLIT_CCTL', 'BCS cache control（初期化で MOCS index を書く）', 'gen12'),
  ('RING_BB_PER_CTX_PTR', 'per-context batch pointer（未使用、0 を書く）', 'gen8+'),
  ('RING_INDIRECT_CTX', 'indirect context pointer（未使用、0）', 'gen8+'),
  ('RING_INDIRECT_CTX_OFFSET', '同 offset（未使用、0）', 'gen8+'),
  ('GEN12_GLOBAL_MOCS', 'global MOCS register 列', 'gen12、has_global_mocs'),
 ]),
 ('割込み（irq.c）', 'irq.c', [
  ('GEN11_GFX_MSTR_IRQ', 'master control（disable→読出し→enable）', 'gen11+'),
  ('GEN11_MASTER_IRQ', 'master enable bit', 'gen11+'),
  ('GEN11_DISPLAY_IRQ', 'display bit（本計画は無視）', 'gen11+'),
  ('GEN11_GU_MISC_IRQ', 'GU misc bit（無視）', 'gen11+'),
  ('GEN11_GT_DW_IRQ', 'GT bank bit', 'gen11+'),
  ('GEN11_GT_INTR_DW', 'GT bank pending dword', 'gen11+'),
  ('GEN11_INTR_IDENTITY_REG', 'identity（class/instance/intr）', 'gen11+'),
  ('GEN11_INTR_DATA_VALID', 'identity valid bit（100 µs 待つ、書いて clear）', 'gen11+'),
  ('GEN11_INTR_ENGINE_CLASS', 'identity class field', 'gen11+'),
  ('GEN11_INTR_ENGINE_INSTANCE', 'identity instance field', 'gen11+'),
  ('GEN11_INTR_ENGINE_INTR', 'identity intr field（16 bit）', 'gen11+'),
  ('GEN11_IIR_REG_SELECTOR', 'bank/bit 選択', 'gen11+'),
  ('GEN11_RENDER_COPY_INTR_ENABLE', 'RCS/BCS class enable（dmask）', 'gen11+'),
  ('GEN11_VCS_VECS_INTR_ENABLE', 'VCS/VECS class enable（0 を書く）', 'gen11+'),
  ('GEN11_RCS0_RSVD_INTR_MASK', 'RCS0 mask（~smask）', 'gen11+'),
  ('GEN11_BCS_RSVD_INTR_MASK', 'BCS0 mask（~smask）', 'gen11+'),
  ('GEN11_VCS0_VCS1_INTR_MASK', 'VCS mask（~0）', 'gen11+'),
  ('GEN11_VCS2_VCS3_INTR_MASK', 'VCS mask（~0）', 'gen11+'),
  ('GEN11_VECS0_VECS1_INTR_MASK', 'VECS mask（~0）', 'gen11+'),
  ('GEN11_GPM_WGBOXPERF_INTR_ENABLE', 'PM enable（0）', 'gen11+'),
  ('GEN11_GPM_WGBOXPERF_INTR_MASK', 'PM mask（~0）', 'gen11+'),
  ('GEN11_GUC_SG_INTR_ENABLE', 'GuC enable（0）', 'gen11+'),
  ('GEN11_GUC_SG_INTR_MASK', 'GuC mask（~0）', 'gen11+'),
  ('GEN11_CRYPTO_RSVD_INTR_ENABLE', 'crypto enable（0）', 'gen11+'),
  ('GEN11_CRYPTO_RSVD_INTR_MASK', 'crypto mask（~0）', 'gen11+'),
  ('GT_RENDER_USER_INTERRUPT', 'MI_USER_INTERRUPT の intr bit', 'gen6+'),
  ('GT_CONTEXT_SWITCH_INTERRUPT', 'CSB 更新の intr bit', 'gen8+'),
  ('GT_CS_MASTER_ERROR_INTERRUPT', 'command streamer error の intr bit', 'gen8+'),
  ('GT_WAIT_SEMAPHORE_INTERRUPT', 'semaphore wait の intr bit（有効化するが yield 処理はしない）', 'gen8+'),
  ('I915_ERROR_INSTRUCTION', 'EMR で唯一 unmask する error bit', 'gen8+'),
 ]),
 ('command（`i915-commands.inc`、request.c / selftest.c / gpu-i915-test）', 'request.c', [
  ('MI_NOOP', 'padding', '全 gen'),
  ('MI_USER_INTERRUPT', 'breadcrumb 後の割込み', '全 gen'),
  ('MI_ARB_CHECK', 'preparser disable（bit8）にも使う', 'gen12: preparser_disable = MI_ARB_CHECK|1<<8|state'),
  ('MI_ARB_ON_OFF', 'arbitration on/off（bb_start の前後）', 'gen8+'),
  ('MI_ARB_ENABLE', 'same', 'gen8+'),
  ('MI_ARB_DISABLE', 'same', 'gen8+'),
  ('MI_BATCH_BUFFER_END', 'batch/ring 終端（LRC image 終端は bit0 を立てる、gen11+）', '全 gen'),
  ('MI_SEMAPHORE_WAIT', 'hang 注入と fence wait（POLL|SAD_GTE）', 'gen8+'),
  ('MI_SEMAPHORE_WAIT_TOKEN', 'gen12 版（dword 数が 1 多い）', 'gen12+'),
  ('MI_SEMAPHORE_POLL', 'poll mode', 'gen8+'),
  ('MI_SEMAPHORE_SAD_EQ_SDD', 'compare op', 'gen8+'),
  ('MI_SEMAPHORE_SAD_GTE_SDD', 'compare op', 'gen8+'),
  ('MI_SEMAPHORE_GLOBAL_GTT', 'GGTT address 指定', 'gen8+'),
  ('MI_STORE_DWORD_IMM_GEN4', 'seqno/store 書込み', 'gen4+（gen8+ は 64 bit address、len 2）'),
  ('MI_USE_GGTT', 'GGTT address 指定（MI_MEM_VIRTUAL と同値）', 'gen8+'),
  ('MI_MEM_VIRTUAL', 'same', 'gen4+'),
  ('MI_LOAD_REGISTER_IMM', 'LRC image の LRI', '全 gen'),
  ('MI_LRI_FORCE_POSTED', 'LRI posted flag', 'gen8+'),
  ('MI_LRI_LRM_CS_MMIO', 'LRI relative mmio flag（LRC image で必須）', 'gen11+'),
  ('MI_LRI_MMIO_REMAP_EN', 'remap（未使用）', 'gen12+'),
  ('MI_STORE_REGISTER_MEM_GEN8', 'register dump（selftest 任意）', 'gen8+'),
  ('MI_SRM_LRM_GLOBAL_GTT', 'same', 'gen8+'),
  ('MI_FLUSH_DW', 'BCS flush + seqno 書込み', 'gen6+'),
  ('MI_FLUSH_DW_STORE_INDEX', 'HWSP index 書込み', 'gen6+'),
  ('MI_FLUSH_DW_OP_STOREDW', 'store dword post-op', 'gen6+'),
  ('MI_FLUSH_DW_USE_GTT', 'GGTT address 指定', 'gen6+'),
  ('MI_INVALIDATE_TLB', 'TLB invalidate（batch 前）', 'gen6+'),
  ('MI_BATCH_BUFFER_START_GEN8', 'batch 起動（bit8 = non-secure/PPGTT）', 'gen8+'),
  ('XY_SRC_COPY_BLT_CMD', '2D copy（gen12 でも有効、tile なし linear のみ使う）', 'gen2+; gen12 では XY_FAST_COPY_BLT も可、本計画は SRC_COPY'),
  ('XY_COLOR_BLT_CMD', '2D fill', 'gen2+'),
  ('BLT_WRITE_RGBA', 'write mask', 'gen2+'),
  ('BLT_WRITE_RGB', 'same', 'gen2+'),
  ('BLT_WRITE_A', 'same', 'gen2+'),
  ('BLT_DEPTH_32', '32 bpp', 'gen2+'),
  ('XY_SRC_COPY_BLT_SRC_TILED', 'tiled flag（使わない、定義のみ）', 'gen4+'),
  ('XY_SRC_COPY_BLT_DST_TILED', 'same', 'gen4+'),
  ('GFX_OP_PIPE_CONTROL', 'RCS flush / seqno 書込み', 'gen6+（gen8+ は 6 dword）'),
  ('PIPE_CONTROL_CS_STALL', 'flush flag', 'gen6+'),
  ('PIPE_CONTROL_QW_WRITE', 'post-sync qword write', 'gen6+'),
  ('PIPE_CONTROL_GLOBAL_GTT_IVB', 'GGTT address 指定', 'gen7+'),
  ('PIPE_CONTROL_FLUSH_ENABLE', 'flush flag', 'gen7+'),
  ('PIPE_CONTROL_TLB_INVALIDATE', 'invalidate flag', 'gen6+'),
  ('PIPE_CONTROL_RENDER_TARGET_CACHE_FLUSH', 'flush flag', 'gen6+'),
  ('PIPE_CONTROL_DEPTH_CACHE_FLUSH', 'flush flag', 'gen6+'),
  ('PIPE_CONTROL_DC_FLUSH_ENABLE', 'flush flag', 'gen6+'),
  ('PIPE_CONTROL_TILE_CACHE_FLUSH', 'flush flag', 'gen11+'),
  ('PIPE_CONTROL_FLUSH_L3', 'flush flag', 'gen12 (<12.70)'),
  ('PIPE_CONTROL_DEPTH_STALL', 'Wa_1409600907 (tgl, adl-p)', 'gen12 (<12.55)'),
  ('PIPE_CONTROL_STORE_DATA_INDEX', 'HWSP index 書込み', 'gen6+'),
  ('PIPE_CONTROL0_HDC_PIPELINE_FLUSH', 'dword0 flag', 'gen12'),
  ('PIPE_CONTROL_COMMAND_CACHE_INVALIDATE', 'invalidate flag', 'gen11+'),
  ('PIPE_CONTROL_INSTRUCTION_CACHE_INVALIDATE', 'invalidate flag', 'gen6+'),
  ('PIPE_CONTROL_TEXTURE_CACHE_INVALIDATE', 'invalidate flag', 'gen6+'),
  ('PIPE_CONTROL_VF_CACHE_INVALIDATE', 'invalidate flag', 'gen6+'),
  ('PIPE_CONTROL_CONST_CACHE_INVALIDATE', 'invalidate flag', 'gen6+'),
  ('PIPE_CONTROL_STATE_CACHE_INVALIDATE', 'invalidate flag', 'gen6+'),
 ]),
 ('logical ring context（`i915-lrc-offsets.inc`、lrc.c）', 'lrc.c', [
  ('LRC_PPHWSP_PN', 'per-process HWSP page index（0）', 'gen8+'),
  ('LRC_PPHWSP_SZ', 'ppHWSP page 数', 'gen8+'),
  ('LRC_STATE_PN', 'register state page index', 'gen8+'),
  ('LRC_STATE_OFFSET', 'register state byte offset', 'gen8+'),
  ('LRC_PPHWSP_SCRATCH', 'flush 用 scratch dword index', 'gen8+'),
  ('LRC_PPHWSP_SCRATCH_ADDR', 'same (bytes)', 'gen8+'),
  ('GEN11_LR_CONTEXT_RENDER_SIZE', 'RCS context image size（14 page）', 'gen11–12'),
  ('GEN8_LR_CONTEXT_OTHER_SIZE', 'BCS context image size（2 page）', 'gen8+'),
  ('CTX_CONTEXT_CONTROL', 'image index', 'gen8+'),
  ('CTX_RING_HEAD', 'image index', 'gen8+'),
  ('CTX_RING_TAIL', 'image index', 'gen8+'),
  ('CTX_RING_START', 'image index', 'gen8+'),
  ('CTX_RING_CTL', 'image index', 'gen8+'),
  ('CTX_BB_STATE', 'image index', 'gen8+'),
  ('CTX_TIMESTAMP', 'image index（0）', 'gen8+'),
  ('CTX_PDP0_UDW', 'PML4 上位', 'gen8+ 4-level'),
  ('CTX_PDP0_LDW', 'PML4 下位', 'gen8+ 4-level'),
  ('CTX_R_PWR_CLK_STATE', 'RPCS（RCS のみ；本計画は 0、full slice 既定に任せる）', 'gen8+'),
  ('gen12_xcs_offsets', 'BCS0 image の LRI 列', 'gen12 (<12.55)'),
  ('gen12_rcs_offsets', 'RCS0 image の LRI 列', 'gen12 (<12.55)'),
  ('NOP', 'offsets encoding: skip', 'lrc.c 内 macro'),
  ('LRI', 'offsets encoding: LRI count/flags', 'lrc.c 内 macro'),
  ('POSTED', 'offsets encoding flag', 'lrc.c 内 macro'),
  ('REG', 'offsets encoding: 7-bit register', 'lrc.c 内 macro'),
  ('REG16', 'offsets encoding: 2-byte register', 'lrc.c 内 macro'),
  ('END', 'offsets encoding terminator', 'lrc.c 内 macro'),
  ('INTEL_LEGACY_64B_CONTEXT', 'descriptor addressing mode（48-bit PPGTT）', 'gen8+'),
  ('GEN8_CTX_VALID', 'descriptor bit', 'gen8+'),
  ('GEN8_CTX_FORCE_RESTORE', 'descriptor bit（毎回 submit で立てる）', 'gen8+'),
  ('GEN8_CTX_L3LLC_COHERENT', 'descriptor bit（gen12 は不使用）', 'gen8–11'),
  ('GEN8_CTX_PRIVILEGE', 'descriptor bit', 'gen8+'),
  ('GEN8_CTX_ADDRESSING_MODE_SHIFT', 'descriptor field shift', 'gen8+'),
  ('GEN8_CTX_ID_SHIFT', 'descriptor ctx id（gen8–10）', 'gen8–10'),
  ('GEN11_SW_CTX_ID_SHIFT', 'descriptor SW ctx id shift（CSB で照合）', 'gen11+'),
  ('GEN11_SW_CTX_ID_WIDTH', 'same width', 'gen11+'),
  ('GEN11_ENGINE_CLASS_SHIFT', 'descriptor engine class（ccid）', 'gen11+'),
  ('GEN11_ENGINE_INSTANCE_SHIFT', 'descriptor engine instance', 'gen11+'),
  ('GEN12_MAX_CONTEXT_HW_ID', 'SW ctx id 上限', 'gen12'),
  ('GEN12_IDLE_CTX_ID', 'CSB の idle ctx id', 'gen12'),
  ('CTX_DESC_FORCE_RESTORE', 'lrc_update_regs が OR する force restore（= GEN8_CTX_FORCE_RESTORE）', 'gen8+'),
  ('GEN11_CSB_ENTRIES', 'CSB entry 数（12）', 'gen11+'),
  ('I915_HWS_CSB_BUF0_INDEX', 'HWSP 内 CSB 先頭 dword index', 'gen8+'),
  ('ICL_HWS_CSB_WRITE_INDEX', 'HWSP 内 CSB write pointer index', 'gen11+'),
  ('INTEL_HWS_CSB_WRITE_INDEX', 'same selector', 'gen11+ は ICL 値'),
  ('I915_GEM_HWS_PREEMPT', 'HWSP preempt semaphore dword（0 固定で使う）', 'gen8+'),
  ('I915_GEM_HWS_SEQNO', 'HWSP seqno dword index', 'gen8+'),
  ('I915_GEM_HWS_SEQNO_ADDR', 'same (bytes)', 'gen8+'),
  ('I915_GEM_HWS_SCRATCH', 'HWSP scratch dword index', 'gen8+'),
  ('GEN12_CTX_STATUS_SWITCHED_TO_NEW_QUEUE', 'CSB lower dword bit', 'gen12'),
  ('GEN12_CTX_SWITCH_DETAIL', 'CSB upper dword field', 'gen12'),
  ('GEN12_CSB_SW_CTX_ID_MASK', 'CSB SW ctx id field', 'gen12'),
  ('GEN12_CSB_CTX_VALID', 'CSB ctx valid 判定', 'gen12'),
  ('EXECLIST_MAX_PORTS', 'port 数上限（zedBSD は 1 port）', 'gen8+'),
 ]),
 ('GTT（`i915-regs.inc`、ggtt.c / ppgtt.c）', 'ggtt.c / ppgtt.c', [
  ('I915_GTT_PAGE_SIZE_4K', 'page size', '全 gen'),
  ('I915_PDES', 'entries per level（512）', 'gen8+'),
  ('I915_PDE_MASK', 'index mask', 'gen8+'),
  ('GEN8_3LVL_PDPES', '3-level PDP 数（不使用、48-bit は 4-level）', 'gen8+'),
  ('GEN8_PAGE_PRESENT', 'PTE/PDE present', 'gen8+'),
  ('GEN8_PAGE_RW', 'PTE/PDE writable', 'gen8+'),
  ('GEN12_PPGTT_PTE_PAT0', 'PPGTT PTE PAT bit0', 'gen12'),
  ('GEN12_PPGTT_PTE_PAT1', 'PPGTT PTE PAT bit1', 'gen12'),
  ('GEN12_PPGTT_PTE_PAT2', 'PPGTT PTE PAT bit2', 'gen12'),
  ('GEN12_GGTT_PTE_LM', 'GGTT PTE local memory（不使用、0）', 'gen12 dgfx'),
  ('GEN12_GGTT_PTE_ADDR_MASK', 'GGTT PTE address field', 'gen12'),
  ('GEN8_PDE_PS_2M', '2 MiB PDE（不使用）', 'gen8+'),
  ('GEN8_PDE_IPS_64K', '64K PDE（不使用）', 'gen8+'),
  ('GEN8_PTE_SHIFT', 'PTE shift（12）', 'gen8+'),
  ('GEN8_PDES', 'PDE 数（512）', 'gen8+'),
 ]),
 ('MOCS（`i915-mocs.inc`、i915.c 初期化）', 'i915.c', [
  ('gen12_mocs_table', 'gen12 MOCS 表（GEN11_MOCS_ENTRIES + 48–61）', 'gen12 (TGL/RKL/DG1/DG2/MTL 以外)'),
  ('GEN11_MOCS_ENTRIES', '共通 entry 2–23', 'gen11+'),
  ('MOCS_ENTRY', 'entry macro', '—'),
  ('_LE_CACHEABILITY', 'control field', '—'),
  ('_LE_TGT_CACHE', 'control field', '—'),
  ('LE_LRUM', 'control field', '—'),
  ('LE_AOM', 'control field', '—'),
  ('LE_SCC', 'control field', '—'),
  ('LE_SCF', 'control field', '—'),
  ('LE_SSE', 'control field', '—'),
  ('LE_1_UC', 'control value', '—'),
  ('LE_3_WB', 'control value', '—'),
  ('LE_TC_1_LLC', 'control value', '—'),
  ('L3_1_UC', 'l3cc value（L3CC は書かない、表のため転記）', '—'),
  ('L3_3_WB', 'same', '—'),
  ('GEN9_NUM_MOCS_ENTRIES', 'entry 数（64）', 'gen9+'),
  ('I915_MOCS_PTE', 'unused entry の既定 index（UAPI enum、gen12 は 2 に上書き）', '—'),
 ]),
]

# Logic re-implemented in zedBSD style; listed so a reviewer can compare behaviour, not text.
LOGIC = [
 ('gen8_gmch_probe / gen8_get_total_gtt_size / ggtt_probe_common', 'gt/intel_ggtt.c', 'ggtt.c: GGTT size from SNB_GMCH_CTRL, PTE window = BAR0 + BAR0/2'),
 ('gen8_ggtt_pte_encode / gen8_set_pte / gen8_ggtt_insert_page / gen8_ggtt_clear_range / gen8_ggtt_invalidate', 'gt/intel_ggtt.c', 'ggtt.c: PTE write (64-bit), scratch fill, flush write'),
 ('gen12_pte_encode / gen8_pde_encode / gen8_init_scratch / gen8_ppgtt_create / __gen8_ppgtt_alloc / __gen8_ppgtt_clear', 'gt/gen8_ppgtt.c', 'ppgtt.c: 4-level table, scratch chain, PAT bits'),
 ('intel_uncore_fw_domains_init (gen11 branch) / fw_domain_wait_ack_*', 'intel_uncore.c', 'uncore.c: GT + RENDER domains only'),
 ('gen11_master_intr_disable / gen11_master_intr_enable / gen11_irq_handler', 'i915_irq.c', 'irq.c: master disable→bank scan→enable'),
 ('gen11_gt_irq_postinstall / gen11_gt_irq_reset / gen11_gt_bank_handler / gen11_gt_engine_identity / gen11_gt_identity_handler', 'gt/intel_gt_irq.c', 'irq.c: enable/mask registers, identity read with valid wait'),
 ('execlists_irq_handler / enable_error_interrupt', 'gt/intel_execlists_submission.c', 'irq.c + engine.c: user interrupt → seqno check, context switch → CSB, CS error → EIR'),
 ('intel_engines[] / intel_engine_setup / intel_engine_context_size / init_status_page / intel_engine_set_hwsp_writemask / intel_engine_stop_cs', 'gt/intel_engine_cs.c', 'engine.c: RCS0/BCS0 only, HWSP page, STOP_RING handshake'),
 ('lrc_init_state / __lrc_init_regs / set_offsets / init_common_regs / init_ppgtt_regs / __reset_stop_ring / lrc_update_regs / lrc_descriptor / lrc_ring_mi_mode / lrc_ring_bb_offset / lrc_ring_wa_bb_per_ctx / lrc_ring_indirect_ptr / lrc_ring_indirect_offset', 'gt/intel_lrc.c', 'lrc.c: image build from offsets table, descriptor'),
 ('execlists_submit_ports / write_desc / reset_csb_pointers / enable_execlists / execlists_reset_prepare / process_csb / csb_read / wa_csb_read / gen12_csb_parse / __gen12_csb_parse / ring_set_paused', 'gt/intel_execlists_submission.c', 'engine.c: ELSQ write, CSB consume, 1 port'),
 ('gen8_engine_reset_prepare / gen8_engine_reset_cancel / gen6_hw_domain_reset / gen8_reset_engines', 'gt/intel_reset.c', 'engine.c: per-engine reset'),
 ('gen8_emit_bb_start / gen8_emit_flush_xcs / gen12_emit_flush_xcs / gen12_emit_flush_rcs / gen12_emit_fini_breadcrumb_xcs / gen12_emit_fini_breadcrumb_rcs / __gen8_emit_flush_dw / gen8_emit_ggtt_write / __gen8_emit_write_rcs / gen12_emit_ggtt_write_rcs / __gen8_emit_pipe_control / preparser_disable', 'gt/gen8_engine_cs.c, gt/gen8_engine_cs.h', 'request.c: ring emission (flush, bb_start, seqno, user interrupt)'),
 ('__init_mocs_table / get_mocs_settings (gen12 branch) / intel_mocs_init', 'gt/intel_mocs.c', 'i915.c: write 64 global MOCS entries, unused → index 2'),
]

FILES = sorted(p for p in TREE.rglob('*') if p.is_file())
TEXT = {p: p.read_text(errors='replace').split('\n') for p in FILES}


def find(symbol):
    hits = []
    define = re.compile(r'^\s*#\s*define\s+%s\b' % re.escape(symbol))
    other = re.compile(r'^[A-Za-z_].*\b%s\b\s*(\[\]|\[\w*\]|\(|=|;|,|$)' % re.escape(symbol))
    member = re.compile(r'^\s+%s\s*(,|=|$)' % re.escape(symbol))
    for path in FILES:
        for number, line in enumerate(TEXT[path], 1):
            if define.match(line) or member.match(line) or (other.match(line) and 'return' not in line and not line.rstrip().endswith(';')
                                      and ('static' in line or 'struct' in line or line.startswith(symbol))):
                hits.append('%s:%d' % (path.relative_to(TREE), number))
    defines = [h for h in hits if define.match(TEXT[TREE / h.rsplit(':', 1)[0]][int(h.rsplit(':', 1)[1]) - 1])]
    return defines or hits


rows = []
missing = []
out = ['<!-- generated by plan/ws029/tests/gen-symbols.py; do not edit by hand -->', '',
       '# WS029 i915: 転記・参照 symbol 一覧（Linux %s）' % TAG, '',
       '各 symbol の出典 file と行番号（`drivers/gpu/drm/i915/` 相対、tag %s、SHA256 は [i915-license-audit.md](i915-license-audit.md)）。'
       '**値は書かない**。値は p002 以降で `src/drivers/gpu/i915/linux/*.inc` へ出典付きで転記する。'
       '「gen12 条件」は ADL-P（graphics ver 12.0、`has_llc`、execlists、GuC なし）での有効条件。' % TAG, '',
       '生成: `python3 plan/ws029/tests/gen-symbols.py %s`（参照 tree は `plan/ws029/tests/fetch-linux-refs.sh` が取得）。' % TAG, '']
for title, users, entries in GROUPS:
    out += ['## %s' % title, '', '利用側: %s' % users, '', '| symbol | 出典 (file:line) | 用途 | gen12 条件 |', '| --- | --- | --- | --- |']
    for symbol, use, cond in entries:
        hits = find(symbol)
        if not hits:
            missing.append(symbol)
        out.append('| `%s` | %s | %s | %s |' % (symbol, ', '.join('`%s`' % h for h in hits) or '**not found**', use, cond))
    out.append('')
out += ['## 論理の参照元（転記せず、挙動を読んで zedBSD 規約で新規に書く）', '',
        '| Linux 関数 | 出典 file | zedBSD 側 |', '| --- | --- | --- |']
for functions, path, target in LOGIC:
    out.append('| %s | `%s` | %s |' % (functions, path, target))
out += ['', '## 未検出', '', ('なし' if not missing else ', '.join('`%s`' % m for m in missing)), '']
OUT.write_text('\n'.join(out))
print('wrote', OUT, 'groups', len(GROUPS), 'symbols', sum(len(g[2]) for g in GROUPS), 'missing', missing)
