include $(dir $(lastword $(MAKEFILE_LIST)))../package.mk

# passwd (ws160-p001), set-user-ID root.
# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
$(eval $(call ZEDBSD_USERLAND_PACKAGE,passwd,passwd,*,y,basic,userland/base/passwd/main.c userland/base/common/account.c userland/base/login/verify.c,y,base,,,4755))
