# zedBSD
# Copyright (C) 2026 Awe Morris
# SPDX-License-Identifier: Zlib

$(eval $(call ZEDBSD_USERLAND_PACKAGE,gpu-recovery-test,GPU isolated recovery test,amd64,n,basic,userland/base/tests/gpu-recovery/main.c,y,base,base/tests/gpu-recovery,,0755,program,,,bin))
