#!/usr/bin/env python3
# ws079-p008: writes userland/base/libpdf/cffdata.c, the fixed data of the Compact Font Format (Adobe Technical
# Note #5176, appendices A to C) that libpdf's charstring fonts use: the 391 standard strings (the glyph names a
# CFF font's charset reaches by SID 0 to 390), StandardEncoding as the SID of each code (the encoding a CFF font
# may name as its own, and the one seac's accented characters are named in, for Type 1 and CFF alike), and the
# predefined Expert and ExpertSubset charsets as SIDs.  The data comes from fontTools (MIT) and its
# StandardEncoding table.
#   python3 plan/ws079/tests/make-cff-tables.py > userland/base/libpdf/cffdata.c
# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
from fontTools.cffLib import cffStandardStrings, cffIExpertStrings, cffExpertSubsetStrings
from fontTools.encodings.StandardEncoding import StandardEncoding

assert len(cffStandardStrings) == 391
sid = {name: index for index, name in enumerate(cffStandardStrings)}
encoding = [sid[name] if name != '.notdef' else 0 for name in StandardEncoding]
expert = [sid[name] for name in cffIExpertStrings]
expert_subset = [sid[name] for name in cffExpertSubsetStrings]


def numbers(values, per_line=16):
    lines = []
    for start in range(0, len(values), per_line):
        lines.append('\t' + ', '.join('%d' % value for value in values[start:start + per_line]) + ',')
    lines[-1] = lines[-1][:-1]
    return '\n'.join(lines)


print('''/*
 * zedBSD
 * Copyright (C) 2026 Awe Morris
 *
 * SPDX-License-Identifier: Zlib
 */

/*
 * The fixed data of the Compact Font Format (Adobe Technical Note #5176,
 * appendices A to C) for libpdf's charstring fonts: the standard strings,
 * StandardEncoding by SID, and the predefined Expert charsets.
 *
 * Generated by plan/ws079/tests/make-cff-tables.py; do not edit.
 */

#include <stddef.h>

#include <pdf.h>

#include "charstrings.h"

/* The standard strings, the glyph names of SIDs 0 to 390. */
const char *const pdf_cff_standard_strings[PDF_CFF_STANDARD_STRINGS] = {''')
for index, name in enumerate(cffStandardStrings):
    end = ',' if index + 1 < len(cffStandardStrings) else ''
    print('\t"%s"%s' % (name, end))
print('''};

/* StandardEncoding: the SID of each code's glyph name (0, .notdef, for an unused code). */
const unsigned short pdf_cff_standard_encoding[256] = {''')
print(numbers(encoding))
print('''};

/* The predefined Expert charset: the SIDs of glyphs 1 onward. */
const unsigned short pdf_cff_expert_charset[] = {''')
print(numbers(expert[1:]))
print('''};

/* The number of glyphs the Expert charset names. */
const size_t pdf_cff_expert_charset_count = sizeof(pdf_cff_expert_charset) / sizeof(pdf_cff_expert_charset[0]);

/* The predefined ExpertSubset charset: the SIDs of glyphs 1 onward. */
const unsigned short pdf_cff_expert_subset_charset[] = {''')
print(numbers(expert_subset[1:]))
print('''};

/* The number of glyphs the ExpertSubset charset names. */
const size_t pdf_cff_expert_subset_charset_count = sizeof(pdf_cff_expert_subset_charset) / sizeof(pdf_cff_expert_subset_charset[0]);''')
