#!/usr/bin/env python3
"""WS031 E-118 round 40: the full-HD textured draw into a PREPARED object (the scanout buffer), from the generated
tex_fixture_fhd_gen.inc; the PPGTT mapping of that object next to its GGTT (display) binding; the VA layout table and
its GPU-free overlap check.  usage: round40.py <repo root>"""
import sys
NL = chr(10)
root = sys.argv[1].rstrip("/") + "/"
I = "src/drivers/gpu/i915/"
P = I + "parity/"
def load(p): return open(root + p).read()
def save(p, s):
    open(root + p, "w").write(s); print("patched", p)
def rep(s, old, new):
    assert s.count(old) == 1, old[:100]
    return s.replace(old, new)

# ---------------- draw_fixture.h
h = load(I + "draw_fixture.h")
h = rep(h, "#endif /* I915_DRAW_FIXTURE_H */", """/*
 * ---- E-118: the same textured draw at 1920x1080, into a buffer the caller owns ----
 * Generated by reftex "1920 1080 rt" (tex_fixture_fhd_gen.inc): the PS computes uv = (pixel + 0.5) / (1920, 1080),
 * the render target's RENDER_SURFACE_STATE comes from isl (B8G8R8A8_UNORM, linear, pitch 7680).  The texture, its
 * surface state and the sampler are the T1 ones.  Nearest sampling at LOD 0 of the 8x8 texture gives
 *   pixel (x, y) = texel (x / 240, y / 135)
 * so the 32x32 fixture's expected_pixel() gives it at (4 * (x / 240), 4 * (y / 135)).
 * GPU VA layout of the draw (checked for overlaps by the GPU-free test, parity_fhd_va_layout()):
 *   0x100400000 +4 KiB   state page (surface heap, dynamic heap, PS, vertices, markers)
 *   0x100401000 +4 KiB   batch
 *   0x100404000 +4 KiB   texture (256 bytes + guard)
 *   0x100800000 +8294400 render target = the scanout buffer's backing (its GGTT binding is separate and unrelated)
 */
#define I915_TEX_FHD_RT_VA        0x100800000ull
#define I915_TEX_FHD_WIDTH        1920u
#define I915_TEX_FHD_HEIGHT       1080u
#define I915_TEX_FHD_PITCH        7680u
#define I915_TEX_FHD_RT_BYTES     8294400u
void drv_i915_tex_fixture_fhd_write_state(void *state_page, uint64_t rt_va, uint64_t tex_va, uint32_t mocs);
unsigned drv_i915_tex_fixture_fhd_build_batch(uint32_t *cmds, unsigned capacity, uint64_t state_va, uint32_t mocs);
/* the generated words, for the GPU-free comparison with the T1 fixture (texture state, sampler, PS size) */
const uint32_t *drv_i915_tex_fixture_fhd_rt_rss(void);
unsigned drv_i915_tex_fixture_fhd_ps_bytes(void);
int drv_i915_tex_fixture_fhd_same_texture_state(void);

#endif /* I915_DRAW_FIXTURE_H */""")
save(I + "draw_fixture.h", h)

# ---------------- selftest.c: the batch knows the RT size; the full-HD writer
st = load(I + "selftest.c")
st = rep(st, "	uint32_t ssp_dw0, ssp_dw1;	/* 3DSTATE_SAMPLER_STATE_POINTERS_PS */" + NL + "};",
         "	uint32_t ssp_dw0, ssp_dw1;	/* 3DSTATE_SAMPLER_STATE_POINTERS_PS */" + NL +
         "	uint32_t rt_w, rt_h;		/* E-118: the render target's size for the drawing rectangle; 0 = the 32x32 fixture */" + NL + "};")
st = rep(st, "	i915_draw_emit(&batch, (I915_DRAW_WIDTH - 1U) | ((I915_DRAW_HEIGHT - 1U) << 16));" + NL + "	i915_draw_emit(&batch, 0U);",
         "	i915_draw_emit(&batch, tex != NULL && tex->rt_w != 0U ? (tex->rt_w - 1U) | ((tex->rt_h - 1U) << 16) :" + NL +
         "		(I915_DRAW_WIDTH - 1U) | ((I915_DRAW_HEIGHT - 1U) << 16));" + NL + "	i915_draw_emit(&batch, 0U);")
st = rep(st, "void" + NL + "drv_i915_tex_fixture_pattern(uint8_t *rgba, unsigned variant)", """/* ---- E-118: the full-HD textured draw (generated shader / render-target / texture words) ---- */

#include "tex_fixture_fhd_gen.inc"

_Static_assert(TEXFHD_PS_BYTES <= I915_DRAW_POSITION_OFFSET - I915_DRAW_PS_KERNEL_OFFSET,
	"the full-HD PS must fit between the kernel offset and the vertex data");
_Static_assert(TEXFHD_PS_DISPATCH_8 == 1U && TEXFHD_PS_NUM_VARYING == 0U && TEXFHD_PS_USES_POS_OFFSET == 0U &&
	TEXFHD_PS_TOTAL_SCRATCH == 0U && TEXFHD_PS_PUSH_SIZE0 == 0U && TEXFHD_3DSTATE_PS_EXTRA_DW0 == 0x784f0000U &&
	(TEXFHD_3DSTATE_PS_DW7 >> 16) == TEXFHD_PS_GRF_START_8,
	"the full-HD PS is dispatched the way this batch dispatches the T1 one");
_Static_assert(TEXFHD_RT_WIDTH == I915_TEX_FHD_WIDTH && TEXFHD_RT_HEIGHT == I915_TEX_FHD_HEIGHT &&
	TEXFHD_RT_ROW_PITCH == I915_TEX_FHD_PITCH && TEXFHD_RT_SIZE == I915_TEX_FHD_RT_BYTES &&
	TEXFHD_RT_VA_PLACEHOLDER == I915_TEX_FHD_RT_VA && TEXFHD_TEX_VA_PLACEHOLDER == I915_TEX_FIXTURE_TEX_VA &&
	TEXFHD_SAMPLER_OFFSET == I915_TEX_FIXTURE_SAMPLER_OFFSET,
	"draw_fixture.h must describe the generated full-HD fixture");

void
drv_i915_tex_fixture_fhd_write_state(void *state_page, uint64_t rt_va, uint64_t tex_va, uint32_t mocs)
{
	uint32_t *heap = state_page;
	uint32_t *rss = &heap[I915_TEX_FIXTURE_TEX_RSS_OFFSET / 4U];
	uint32_t *rt = &heap[I915_DRAW_SURFACE_STATE_OFFSET / 4U];

	drv_i915_draw_fixture_write_state(state_page, rt_va, mocs);
	/* the render target's surface state is isl's (render-target usage, 1920x1080, pitch 7680), address patched in */
	memcpy(rt, texfhd_rt_rss, sizeof(texfhd_rt_rss));
	rt[8] = (uint32_t)rt_va;
	rt[9] = (uint32_t)(rt_va >> 32);
	/* the full-HD sampling PS and its EOT carpet */
	memset((uint8_t *)state_page + I915_DRAW_PS_KERNEL_OFFSET, 0, I915_DRAW_POSITION_OFFSET - I915_DRAW_PS_KERNEL_OFFSET);
	memcpy((uint8_t *)state_page + I915_DRAW_PS_KERNEL_OFFSET, texfhd_ps, TEXFHD_PS_BYTES);
	i915_draw_fill_eot(state_page, I915_DRAW_PS_KERNEL_OFFSET + TEXFHD_PS_BYTES,
		I915_DRAW_POSITION_OFFSET - I915_DRAW_PS_KERNEL_OFFSET - TEXFHD_PS_BYTES);
	/* binding table entry 1 -> the texture (the T1 surface state), sampler */
	heap[I915_DRAW_BINDING_TABLE_OFFSET / 4U + 1U] = I915_TEX_FIXTURE_TEX_RSS_OFFSET;
	memcpy(rss, texfhd_tex_rss, sizeof(texfhd_tex_rss));
	rss[8] = (uint32_t)tex_va;
	rss[9] = (uint32_t)(tex_va >> 32);
	memcpy(&heap[I915_TEX_FIXTURE_SAMPLER_OFFSET / 4U], texfhd_sampler, sizeof(texfhd_sampler));
	/* the RECTLIST covers the whole target: (1920, 1080), (0, 1080), (0, 0) */
	i915_draw_write_vertices(state_page, 0x44f00000U /* 1920.0f */, 0x44870000U /* 1080.0f */);
	(void)mocs;     /* the generated surface states carry MOCS 6 = GEN12_MOCS(I915_MOCS_UNCACHED_INDEX) (checked by the test) */
}

unsigned
drv_i915_tex_fixture_fhd_build_batch(uint32_t *cmds, unsigned capacity, uint64_t state_va, uint32_t mocs)
{
	static const struct i915_draw_tex_opts tex = {
		TEXFHD_3DSTATE_PS_DW3, TEXFHD_3DSTATE_PS_DW7, TEXFHD_3DSTATE_PS_EXTRA_DW1,
		TEXFHD_SAMPLER_POINTERS_PS_DW0, TEXFHD_SAMPLER_POINTERS_PS_DW1, TEXFHD_RT_WIDTH, TEXFHD_RT_HEIGHT,
	};
	static struct i915_gem_object state;

	memset(&state, 0, sizeof(state));
	state.va = state_va;
	return i915_draw_build_batch(cmds, capacity, &state, &state, &state, &state, mocs, 1U, &tex);
}

const uint32_t *
drv_i915_tex_fixture_fhd_rt_rss(void)
{
	return texfhd_rt_rss;
}

unsigned
drv_i915_tex_fixture_fhd_ps_bytes(void)
{
	return TEXFHD_PS_BYTES;
}

/* the texture state, the sampler and the packet words must be the T1 ones: only the scale and the target differ */
int
drv_i915_tex_fixture_fhd_same_texture_state(void)
{
	return memcmp(texfhd_tex_rss, texfix_tex_rss, sizeof(texfix_tex_rss)) == 0 &&
		memcmp(texfhd_sampler, texfix_sampler, sizeof(texfix_sampler)) == 0 &&
		TEXFHD_3DSTATE_PS_DW3 == TEXFIX_3DSTATE_PS_DW3 && TEXFHD_3DSTATE_PS_DW7 == TEXFIX_3DSTATE_PS_DW7 &&
		TEXFHD_3DSTATE_PS_EXTRA_DW1 == TEXFIX_3DSTATE_PS_EXTRA_DW1 &&
		TEXFHD_SAMPLER_POINTERS_PS_DW1 == TEXFIX_SAMPLER_POINTERS_PS_DW1;
}

void
drv_i915_tex_fixture_pattern(uint8_t *rgba, unsigned variant)""")
save(I + "selftest.c", st)

# ---------------- eu_test: render into a prepared object
eh = load(P + "eu_test.h")
eh = rep(eh, "int parity_tex_test_run(struct parity_tex_test *x, struct parity_gt_engines *es,",
         """/*
 * E-118: the full-HD textured draw into an object the CALLER owns (the scanout buffer): it is mapped into the PPGTT at
 * I915_TEX_FHD_RT_VA page by page (the same backing pages as its GGTT display binding), pre-filled and published by the
 * CPU, drawn by the GPU, and compared pixel by pixel after the request retired and the CPU view was invalidated.  The
 * object is never written by the CPU after the draw, and never freed here.
 */
struct parity_fhd_render {
	struct parity_eu_test t;
	struct parity_gt_object *tex;
	struct parity_gt_object *rt;           /* NOT owned */
	uint32_t mocs, rt_rss_mocs;
	uint32_t marker_before, marker_middraw, marker_after, ps_marker;
	unsigned px_match, px_stale, px_total;
	int first_bad_x, first_bad_y;
	uint32_t first_bad_expected, first_bad_observed;
	unsigned tex_changed_bytes, guard_bad_bytes;
	unsigned rt_pages, rt_pages_mapped, rt_pages_cleared;
	int rt_walk_ok;                        /* first / middle / last page: the PPGTT leaf is the object's own page */
	uint64_t rt_first_dma, rt_last_dma;
	int gpu_done;                          /* request retired and engine parked: the GPU no longer uses the target */
	uint64_t image_hash;
};
int parity_fhd_render_run(struct parity_fhd_render *x, struct parity_gt_engines *es, struct parity_gt_ppgtt *vm,
	struct parity_gt_mem *gm, struct osdep_mmio *m, struct spinlock *uncore_lock, unsigned timeout_ms,
	struct parity_gt_object *rt);
/* wrong pixels of the target against the expected image (no CPU write) */
uint32_t parity_fhd_render_verify(const struct parity_fhd_render *x, const uint32_t *pixels, uint32_t pitch_bytes);
/* PTEs of the target back to scratch, own objects freed -- only when gpu_done; the target itself is never touched */
int parity_fhd_render_release(struct parity_fhd_render *x, struct parity_gt_mem *gm, struct parity_gt_ppgtt *vm);
/* the VA layout table of the draw and its overlap check (GPU-free): 0 = no two ranges overlap, all aligned */
struct parity_fhd_va { const char *name; uint64_t va, len, align; };
int parity_fhd_va_layout(const struct parity_fhd_va **out, unsigned *n);

int parity_tex_test_run(struct parity_tex_test *x, struct parity_gt_engines *es,""")
save(P + "eu_test.h", eh)

e = load(P + "eu_test.c")
e = rep(e, "/* ---------------- T3: texture update, binding switch, redraw, new context ---------------- */", r'''/* ---------------- E-118: the full-HD draw into the scanout buffer ---------------- */

#define FHD_PREFILL 0x5a5a5a5au

static const struct parity_fhd_va fhd_va[] = {
	{ "state page", PARITY_EU_SHARED_VA, 4096u, 4096u },
	{ "batch", PARITY_EU_BATCH_VA, 4096u, 4096u },
	{ "texture", I915_TEX_FIXTURE_TEX_VA, 4096u, 4096u },
	{ "render target = scanout backing", I915_TEX_FHD_RT_VA, (I915_TEX_FHD_RT_BYTES + 4095u) & ~4095u, 4096u },
};

int
parity_fhd_va_layout(const struct parity_fhd_va **out, unsigned *n)
{
	unsigned i, j, nn = (unsigned)(sizeof(fhd_va) / sizeof(fhd_va[0]));

	if (out != 0)
		*out = fhd_va;
	if (n != 0)
		*n = nn;
	for (i = 0u; i < nn; i++) {
		if ((fhd_va[i].va & (fhd_va[i].align - 1u)) != 0u || fhd_va[i].len == 0u)
			return -1;
		for (j = i + 1u; j < nn; j++)
			if (fhd_va[i].va < fhd_va[j].va + fhd_va[j].len && fhd_va[j].va < fhd_va[i].va + fhd_va[i].len)
				return -1;
	}
	return 0;
}

uint32_t
parity_fhd_render_verify(const struct parity_fhd_render *x, const uint32_t *pixels, uint32_t pitch_bytes)
{
	static uint8_t pattern[I915_TEX_FIXTURE_TEX_BYTES];
	uint32_t bad = 0u, xx, yy;

	(void)x;
	drv_i915_tex_fixture_pattern(pattern, 0u);
	for (yy = 0u; yy < I915_TEX_FHD_HEIGHT; yy++) {
		const uint32_t *row = (const uint32_t *)((const uint8_t *)pixels + (uint64_t)yy * pitch_bytes);
		uint32_t row_want[8];
		unsigned u;

		for (u = 0u; u < 8u; u++)                       /* texel column u covers x in [240u, 240u + 240) */
			row_want[u] = drv_i915_tex_fixture_expected_pixel(pattern, 4u * u, 4u * (yy / 135u));
		for (xx = 0u; xx < I915_TEX_FHD_WIDTH; xx++)
			if (row[xx] != row_want[xx / 240u])
				bad++;
	}
	return bad;
}

int
parity_fhd_render_run(struct parity_fhd_render *x, struct parity_gt_engines *es, struct parity_gt_ppgtt *vm,
	struct parity_gt_mem *gm, struct osdep_mmio *m, struct spinlock *uncore_lock, unsigned timeout_ms,
	struct parity_gt_object *rt)
{
	static const uint64_t va[3] = { PARITY_EU_SHARED_VA, PARITY_EU_BATCH_VA, I915_TEX_FIXTURE_TEX_VA };
	static uint8_t pattern[I915_TEX_FIXTURE_TEX_BYTES];
	struct parity_eu_test *t;
	struct parity_gt_engine *ge;
	struct parity_execlists *el;
	struct parity_gt_object *obj[3];
	struct parity_gt_ppgtt_walk w;
	volatile uint32_t *mk;
	volatile uint8_t *tb;
	uint64_t dma;
	unsigned i, p;
	int rc;

	if (x == 0 || es == 0 || vm == 0 || gm == 0 || m == 0 || rt == 0 || rt->bytes < I915_TEX_FHD_RT_BYTES)
		return -EINVAL;
	memset(x, 0, sizeof(*x));
	t = &x->t;
	x->rt = rt;
	x->first_bad_x = -1;
	x->first_bad_y = -1;
	if (parity_fhd_va_layout(0, 0) != 0)
		return fail(t, -EINVAL, "va layout overlaps");

	for (i = 0u; i < es->n; i++)
		if (es->ge[i].info->class == PARITY_RENDER_CLASS)
			break;
	if (i == es->n)
		return fail(t, -ENODEV, "no render engine");
	t->engine_idx = i;
	ge = &es->ge[i];
	el = &es->el[i];

	t->shared = parity_gt_object_create(gm, 4096u);
	t->batch = parity_gt_object_create(gm, 4096u);
	x->tex = parity_gt_object_create(gm, 4096u);
	if (t->shared == 0 || t->batch == 0 || x->tex == 0)
		return fail(t, -ENOMEM, "gem_create");
	obj[0] = t->shared; obj[1] = t->batch; obj[2] = x->tex;
	rc = parity_gt_ppgtt_alloc_range(gm, vm, PARITY_EU_SHARED_VA, 5u * 4096u);
	if (rc == 0)
		rc = parity_gt_ppgtt_alloc_range(gm, vm, I915_TEX_FHD_RT_VA, (uint64_t)rt->pages * 4096u);
	if (rc != 0)
		return fail(t, rc, "allocate_va_range");
	for (i = 0u; i < 3u && rc == 0; i++) {
		rc = parity_gt_object_page_dma(obj[i], 0u, &dma);
		if (rc == 0)
			rc = parity_gt_ppgtt_insert_page(vm, dma, va[i], 0u);
	}
	/* the render target: every page of the scanout buffer's own backing */
	x->rt_pages = (I915_TEX_FHD_RT_BYTES + 4095u) / 4096u;
	for (p = 0u; p < x->rt_pages && rc == 0; p++) {
		rc = parity_gt_object_page_dma(rt, p, &dma);
		if (rc == 0)
			rc = parity_gt_ppgtt_insert_page(vm, dma, I915_TEX_FHD_RT_VA + (uint64_t)p * 4096u, 0u);
		if (rc == 0)
			x->rt_pages_mapped++;
	}
	if (rc != 0)
		return fail(t, rc, "ppgtt_insert");
	/* what the GPU will walk: the leaf of the first, a middle and the last page is the object's own page */
	x->rt_walk_ok = 1;
	for (i = 0u; i < 3u; i++) {
		unsigned pg = i == 0u ? 0u : i == 1u ? x->rt_pages / 2u : x->rt_pages - 1u;

		if (parity_gt_object_page_dma(rt, pg, &dma) != 0 || parity_gt_ppgtt_walk(vm, I915_TEX_FHD_RT_VA + (uint64_t)pg * 4096u, &w) != 0 ||
		    w.levels != 4 || !w.leaf_present || w.leaf_dma != (dma & ~0xfffull))
			x->rt_walk_ok = 0;
		if (i == 0u)
			x->rt_first_dma = dma;
		if (i == 2u)
			x->rt_last_dma = dma;
	}
	if (!x->rt_walk_ok)
		return fail(t, -EFAULT, "render target PPGTT walk");

	/* CPU uploads: texture (+ guard), state page, batch; the target pre-filled and published for the GPU */
	x->mocs = drv_i915_draw_fixture_mocs();
	drv_i915_tex_fixture_pattern(pattern, 0u);
	tb = (volatile uint8_t *)x->tex->cpu;
	for (i = 0u; i < 4096u; i++)
		tb[i] = i < I915_TEX_FIXTURE_TEX_BYTES ? pattern[i] : (uint8_t)PARITY_TEX_GUARD_BYTE;
	{
		uint32_t *px = (uint32_t *)rt->cpu;

		for (i = 0u; i < I915_TEX_FHD_RT_BYTES / 4u; i++)
			px[i] = FHD_PREFILL;
		parity_gt_clflush(rt->cpu, I915_TEX_FHD_RT_BYTES);
	}
	drv_i915_tex_fixture_fhd_write_state(t->shared->cpu, I915_TEX_FHD_RT_VA, I915_TEX_FIXTURE_TEX_VA, x->mocs);
	x->rt_rss_mocs = (((uint32_t *)t->shared->cpu)[64u / 4u + 1u] >> 24) & 0x7fu;
	if (x->rt_rss_mocs != x->mocs)
		return fail(t, -EINVAL, "render target surface state MOCS");
	t->batch_dwords = drv_i915_tex_fixture_fhd_build_batch((uint32_t *)t->batch->cpu, 1024u, PARITY_EU_SHARED_VA, x->mocs);
	if (t->batch_dwords == 0u || t->batch_dwords >= 1024u)
		return fail(t, -ENOSPC, "build_batch");
	t->pipesel_rc = parity_draw_batch_check_pipeline_select((const uint32_t *)t->batch->cpu, t->batch_dwords, &t->pipesel);
	if (t->pipesel_rc != 0)
		return fail(t, t->pipesel_rc, "pipeline_select_verify");
	t->batch_hash = fnv1a64(t->batch->cpu, (size_t)t->batch_dwords * 4u, 0xcbf29ce484222325ull);

	rc = parity_lrc_alloc(&t->ce, ge, vm, gm, 4096u, 0u);
	if (rc != 0)
		return fail(t, rc, "intel_context_create");
	t->tl_page = parity_gt_object_create(gm, 4096u);
	if (t->tl_page == 0)
		return fail(t, -ENOMEM, "intel_timeline_create");
	rc = parity_gt_ggtt_bind(gm, t->tl_page);
	if (rc != 0)
		return fail(t, rc, "intel_timeline_pin");
	parity_lrc_init_state(&t->ce);
	(void)parity_lrc_update_regs(&t->ce, t->ce.ring.tail);
	t->tl_seqno = 2u;
	rc = eu_build_request(t, &t->rq, &t->ce, t->tl_page, t->tl_seqno, PARITY_EU_BATCH_VA);
	if (rc != 0)
		return rc;
	rc = parity_execlists_submit(ge, el, m, &t->rq);
	if (rc != 0)
		return fail(t, rc, "execlists_submit");
	t->submitted = 1;
	rc = wait_retired(t, ge, el, &t->rq, m, timeout_ms);
	if (rc == 0)
		t->completed = 1;
	else if (rc == -ETIMEDOUT)
		t->timed_out = 1;
	else
		(void)fail(t, rc, "i915_request_wait");

	mk = (volatile uint32_t *)t->shared->cpu + I915_DRAW_FIXTURE_MARKER_OFFSET / 4u;
	x->marker_before = mk[0];
	x->marker_after = mk[1];
	x->marker_middraw = mk[2];
	x->ps_marker = mk[4];
	if (t->completed) {
		eu_log_record(t, ge, el, &t->rq, &t->ce, "completed");
		t->parked = eu_park(t, es, ge, el, m, timeout_ms);
		x->gpu_done = t->parked;
		/* the CPU view: drop any line the CPU may hold for these pages before reading what the GPU wrote */
		parity_gt_clflush(rt->cpu, I915_TEX_FHD_RT_BYTES);
		{
			const uint32_t *px = (const uint32_t *)rt->cpu;
			static uint8_t pat[I915_TEX_FIXTURE_TEX_BYTES];
			uint32_t yy, xx;

			drv_i915_tex_fixture_pattern(pat, 0u);
			x->px_total = I915_TEX_FHD_WIDTH * I915_TEX_FHD_HEIGHT;
			for (yy = 0u; yy < I915_TEX_FHD_HEIGHT; yy++) {
				for (xx = 0u; xx < I915_TEX_FHD_WIDTH; xx++) {
					uint32_t want = drv_i915_tex_fixture_expected_pixel(pat, 4u * (xx / 240u), 4u * (yy / 135u));
					uint32_t got = px[yy * (I915_TEX_FHD_PITCH / 4u) + xx];

					if (got == want) {
						x->px_match++;
					} else {
						if (got == FHD_PREFILL)
							x->px_stale++;
						if (x->first_bad_x < 0) {
							x->first_bad_x = (int)xx;
							x->first_bad_y = (int)yy;
							x->first_bad_expected = want;
							x->first_bad_observed = got;
						}
					}
				}
			}
			x->image_hash = fnv1a64(rt->cpu, I915_TEX_FHD_RT_BYTES, 0xcbf29ce484222325ull);
		}
		for (i = 0u; i < 4096u; i++) {
			uint8_t want = i < I915_TEX_FIXTURE_TEX_BYTES ? pattern[i] : (uint8_t)PARITY_TEX_GUARD_BYTE;

			if (tb[i] != want) {
				if (i < I915_TEX_FIXTURE_TEX_BYTES)
					x->tex_changed_bytes++;
				else
					x->guard_bad_bytes++;
			}
		}
		t->outcome = (t->parked && x->marker_before == I915_DRAW_FIXTURE_MARKER_BEFORE &&
			x->marker_middraw == I915_DRAW_FIXTURE_MARKER_MIDDRAW && x->marker_after == I915_DRAW_FIXTURE_MARKER_AFTER &&
			x->ps_marker == I915_DRAW_FIXTURE_PS_MARKER && x->px_match == x->px_total &&
			x->tex_changed_bytes == 0u && x->guard_bad_bytes == 0u) ? PARITY_EU_PASS : PARITY_EU_ERROR;
		if (t->outcome == PARITY_EU_ERROR && t->err == 0)
			(void)fail(t, -EIO, "markers/pixels/guard");
		return t->err;
	}
	if (t->timed_out)
		t->outcome = PARITY_EU_HANG;
	eu_log_record(t, ge, el, &t->rq, &t->ce, "hang");
	eu_hang_dump_reset(t, es, ge, el, m, uncore_lock);
	/* gpu_done stays 0: after a hang the GPU is not shown to have let go of the target; the caller keeps it */
	return t->err != 0 ? t->err : -ETIMEDOUT;
}

int
parity_fhd_render_release(struct parity_fhd_render *x, struct parity_gt_mem *gm, struct parity_gt_ppgtt *vm)
{
	unsigned p;

	if (x == 0 || gm == 0 || vm == 0)
		return -EINVAL;
	if (!x->gpu_done && x->t.submitted)
		return -EBUSY;                  /* the GPU may still use the target and the state: nothing is released */
	/* the render target's PTEs back to scratch: nothing in this vm names the scanout pages any more */
	for (p = 0u; p < x->rt_pages_mapped; p++)
		if (parity_gt_ppgtt_insert_scratch(vm, I915_TEX_FHD_RT_VA + (uint64_t)p * 4096u) == 0)
			x->rt_pages_cleared++;
	if (x->tex != 0) {
		parity_gt_object_destroy(gm, x->tex);
		x->tex = 0;
	}
	parity_eu_test_release(&x->t, gm);
	x->rt = 0;
	return x->rt_pages_cleared == x->rt_pages_mapped ? 0 : -EIO;
}

/* ---------------- T3: texture update, binding switch, redraw, new context ---------------- */''')
save(P + "eu_test.c", e)

# ---------------- gt_mem: a PTE back to scratch
gh = load(P + "gt_mem.h")
gh = rep(gh, "/* gen8_ppgtt_insert_entry(): one PTE at offset; the tables must exist. */",
         "/* gen8_ppgtt_clear(): one PTE at offset back to the scratch page (the vm's scratch encode); the tables stay. */" + NL +
         "int parity_gt_ppgtt_insert_scratch(struct parity_gt_ppgtt *pp, uint64_t offset);" + NL + NL +
         "/* gen8_ppgtt_insert_entry(): one PTE at offset; the tables must exist. */")
save(P + "gt_mem.h", gh)
g = load(P + "gt_mem.c")
g = rep(g, "#define PTE_ADDR_MASK   0x0000fffffffff000ull", """int
parity_gt_ppgtt_insert_scratch(struct parity_gt_ppgtt *pp, uint64_t offset)
{
	struct parity_gt_object *table;
	struct parity_gt_ppgtt_table *t;
	uint64_t idx;
	int lvl;

	if (pp == 0 || !pp->inited || (offset & (PARITY_GT_PAGE_BYTES - 1u)) != 0u)
		return -EINVAL;
	idx = offset >> 12;
	table = pp->top_pd;
	for (lvl = pp->top; lvl > 0; lvl--) {
		t = child_of(pp, table, (unsigned)((idx >> ((unsigned)lvl * 9u)) & 511u));
		if (t == 0)
			return -ENOENT;
		table = t->obj;
	}
	((uint64_t *)table->cpu)[idx & 511u] = pp->scratch_encode[0];
	parity_gt_clflush(&((uint64_t *)table->cpu)[idx & 511u], sizeof(uint64_t));
	return 0;
}

#define PTE_ADDR_MASK   0x0000fffffffff000ull""")
save(P + "gt_mem.c", g)
print("done")
