#!/usr/bin/env python3
"""Compile the compute test's shaders (ws101-p005, the scenario "vkcs") and write the SPIR-V the kernel test embeds."""
# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
#
# usage: python3 src/drivers/gpu/i915/tests/render/compute-shaders/regenerate.py
#
# Writes spill.comp (from the template below), <name>.spv next to each GLSL source and
# tests/fixtures/compute-shaders-gen.inc (included by tests/render/compute.c).  The file holds the SPIR-V words
# and the sizes of the spill step only: the scenario computes every expected word itself, in integers, from
# the formulas its comments give (the kernel has no FPU), so the numbers stay small and the file short.
import hashlib
import pathlib
import subprocess

# Source, stage, C array, optimization.  The spill step's SPIR-V is optimized (-O: 12 KiB where -O0 makes 29 KiB,
# the test kernel is near its size limit); its values stay live to the sum, and it still spills.
SHADERS = (
    ('one.comp', 'compute', 'i915_vkcs_one_comp', '-O0'),
    ('add.comp', 'compute', 'i915_vkcs_add_comp', '-O0'),
    ('ids.comp', 'compute', 'i915_vkcs_ids_comp', '-O0'),
    ('odd.comp', 'compute', 'i915_vkcs_odd_comp', '-O0'),
    ('push.comp', 'compute', 'i915_vkcs_push_comp', '-O0'),
    ('atomic.comp', 'compute', 'i915_vkcs_atomic_comp', '-O0'),
    ('mixed.comp', 'compute', 'i915_vkcs_mixed_comp', '-O0'),
    ('mixed.vert', 'vertex', 'i915_vkcs_mixed_vert', '-O0'),
    ('mixed.frag', 'fragment', 'i915_vkcs_mixed_frag', '-O0'),
    ('inc.comp', 'compute', 'i915_vkcs_inc_comp', '-O0'),
    ('spill.comp', 'compute', 'i915_vkcs_spill_comp', '-O'),
    # ws101-p006: shared memory and barriers, and three modules the compiler must refuse.
    ('shared.comp', 'compute', 'i915_vkcs_shared_comp', '-O0'),
    ('reduce.comp', 'compute', 'i915_vkcs_reduce_comp', '-O0'),
    ('scan.comp', 'compute', 'i915_vkcs_scan_comp', '-O0'),
    ('oddbar.comp', 'compute', 'i915_vkcs_oddbar_comp', '-O0'),
    ('atomsh.comp', 'compute', 'i915_vkcs_atomsh_comp', '-O0'),
    ('refuse/big.comp', 'compute', 'i915_vkcs_refuse_big_comp', '-O0'),
    ('refuse/retbar.comp', 'compute', 'i915_vkcs_refuse_retbar_comp', '-O0'),
    ('refuse/loopbar.comp', 'compute', 'i915_vkcs_refuse_loopbar_comp', '-O0'),
)

# The spill step: this many values live at once, each x * (k + 1) + y; the sum pairs value k with value
# (k * SPILL_STRIDE + SPILL_SHIFT) % SPILL_VALUES.
SPILL_VALUES = 120
SPILL_STRIDE = 37
SPILL_SHIFT = 11

HEADER = """/*
 * zedBSD
 * Copyright (C) 2026 Awe Morris
 *
 * SPDX-License-Identifier: Zlib
 */
"""


def run(arguments):
    """Runs one tool and returns what it printed."""
    return subprocess.run(arguments, check=True, timeout=60, stdin=subprocess.DEVNULL,
                          stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True).stdout.strip()


def spill_source():
    """The spill step's GLSL: more values live at once than the EU has registers, and a loop among them."""
    lines = [HEADER]
    lines.append('/*')
    lines.append(' * GENERATED by regenerate.py (SPILL_VALUES %d) - SPILL: %d values made from' % (SPILL_VALUES, SPILL_VALUES))
    lines.append(' * the invocation are all live until the sum at the end, and a loop whose trip')
    lines.append(' * count differs from lane to lane updates two variables while they are.  The')
    lines.append(' * compiler spills to scratch memory; enough groups run to fill every thread.')
    lines.append(' */')
    lines.append('#version 450')
    lines.append('')
    lines.append('layout(local_size_x = 64) in;')
    lines.append('')
    lines.append('layout(std430, set = 0, binding = 0) buffer O { uint o[]; };')
    lines.append('')
    lines.append('void main()')
    lines.append('{')
    lines.append('    uint x = gl_GlobalInvocationID.x;')
    lines.append('    uint y = (x * 2654435761u) >> 7;')
    for k in range(SPILL_VALUES):
        lines.append('    uint t%d = x * %du + y;' % (k, k + 1))
    lines.append('    uint a = t7;')
    lines.append('    uint b = t50;')
    lines.append('    uint n = (x + y) % 5u;')
    lines.append('    uint s = 0u;')
    lines.append('')
    lines.append('    for (uint i = 0u; i < n; i++) {')
    lines.append('        a = a * 3u + t3;')
    lines.append('        b = b + t90 * 5u - a;')
    lines.append('    }')
    for k in reversed(range(SPILL_VALUES)):
        lines.append('    s += t%d * t%d;' % (k, (k * SPILL_STRIDE + SPILL_SHIFT) % SPILL_VALUES))
    lines.append('    o[x] = s + a + b;')
    lines.append('}')
    return '\n'.join(lines) + '\n'


def c_words(lines, symbol, words, per_line=6):
    """A C array of 32-bit words."""
    lines.append('static const uint32_t %s[%d] = {' % (symbol, len(words)))
    for start in range(0, len(words), per_line):
        lines.append('\t' + ' '.join('0x%08xU,' % w for w in words[start:start + per_line]))
    lines.append('};')


def main():
    here = pathlib.Path(__file__).resolve().parent
    fixtures = here.parent.parent / 'fixtures'
    (here / 'spill.comp').write_text(spill_source())
    version = run(['glslc', '--version']).splitlines()[0]
    lines = [HEADER]
    lines.append('/*')
    lines.append(' * GENERATED FILE - the SPIR-V of the compute test (ws101-p005, the scenario "vkcs").')
    lines.append(' * Do not edit by hand.')
    lines.append(' *')
    lines.append(' * Generator : src/drivers/gpu/i915/tests/render/compute-shaders/regenerate.py')
    lines.append(' * Compiler  : %s (--target-env=vulkan1.1 --target-spv=spv1.0, -O0; spill.comp -O)' % version)
    lines.append(' */')
    lines.append('')
    lines.append('/* The spill step\'s values and its pairing (see regenerate.py). */')
    lines.append('#define I915_VKCS_SPILL_VALUES\t\t%dU' % SPILL_VALUES)
    lines.append('#define I915_VKCS_SPILL_STRIDE\t\t%dU' % SPILL_STRIDE)
    lines.append('#define I915_VKCS_SPILL_SHIFT\t\t%dU' % SPILL_SHIFT)
    for source, stage, symbol, optimization in SHADERS:
        path = here / source
        spv = here / (source + '.spv')
        run(['glslc', '--target-env=vulkan1.1', '--target-spv=spv1.0', optimization, '-fshader-stage=' + stage,
             '-o', str(spv), str(path)])
        run(['spirv-val', '--target-env', 'vulkan1.1', str(spv)])
        data = spv.read_bytes()
        words = [int.from_bytes(data[i:i + 4], 'little') for i in range(0, len(data), 4)]
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        lines.append('')
        lines.append('/* %s (sha256 %s), %d words. */' % (source, digest, len(words)))
        c_words(lines, symbol, words)
    lines.append('')
    (fixtures / 'compute-shaders-gen.inc').write_text('\n'.join(lines))


main()
