#!/bin/sh
# ws075-p013 (H4): builds the demonstration image (plan/ws075/demo/config-demo-hdmi.mk): the graphical boot to the
# greeter and the session on the HDMI display (display=hdmi), App Home with the demonstration's applications
# (plan/ws035/demo/apps.conf: Files, Notes, Terminal, PDF Viewer, Browser, Model viewer, Gears, X terminal), the
# wallpaper, the wallpapers Settings offers (generated by the build, ZEDBSD_KEILAND_WALLPAPERS := y in the config) and
# the pictures kept in the tree (userland/desktop/keiland/wallpapers/, 2026-10-03 user).  The accounts are the base
# system's (2026-09-29: root/root, kei/kei; kei is logged in by itself at boot).  sessiond waits for the i915's GPU
# node while the kernel reports the device still attaching (hw.gpu.attaching, BUG-092).
# ws136-p001 (2026-10-04): the image is a config.mk build plus files of the tree (plan/tools/guest/test-image.sh).
# The fonts come with the compositor's package (userland/desktop/fonts/); the wallpaper is
# userland/desktop/keiland/wallpapers/Birch-Lake.ppm.
#
#   plan/ws075/demo/build-demo-image.sh [BUILD] [passthrough] [MAKE ARGUMENTS...]     (default build/demo-hdmi)
#
# The image is BUILD/hdd-image.img; write it to a USB stick and boot the machine from it (UEFI), or edit the boot
# parameters afterwards in zedbsd.cfg on its ESP (docs/reference/kernel-boot-parameters.md).
# "passthrough" is the image for the 5330's QEMU passthrough (plan/ws075/tests/hdmi-h4-hw.sh): the guest sees no
# OpRegion there, so the kernel carries the machine's captured VBT (I915_TEST_VBT=y).  On the machine itself the VBT
# comes from its OpRegion and the word is left out.  Further words go to make, e.g.
# "ZEDBSD_BOOT_EXTRA_LINES=display=hdmi display.mode=1920x1080@60" or ZEDBSD_TEST_CPPFLAGS=-DI915_TEST_HDMI_ABSENT=1.
# Give each variant a build directory of its own: make does not see a change of the C flags.
# The guest harness's public key lets plan/tools/guest/guest.sh-style ssh reach root on the machine.
# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
set -eu
cd "$(dirname -- "$0")/../../.."
build=${1:-build/demo-hdmi}
[ $# -gt 0 ] && shift
vbt=n
if [ "${1:-}" = passthrough ]; then
	vbt=y
	shift
fi
key=plan/tmp/guest/id_ed25519.pub
[ -f "$key" ] || python3 plan/tools/guest/guest.py extra-files >/dev/null
for picture in userland/desktop/keiland/wallpapers/*.ppm; do
	set -- "$@" --file "/usr/share/keiland/wallpapers/$(basename "$picture")=$picture"
done
plan/tools/guest/test-image.sh --no-harness plan/ws075/demo/config-demo-hdmi.mk "$build" \
	--file /etc/keiland/apps.conf=plan/ws035/demo/apps.conf \
	--file /usr/share/keiland/wallpaper.ppm=userland/desktop/keiland/wallpapers/Birch-Lake.ppm \
	--file /root/.ssh/authorized_keys=$key --mode /root/.ssh/authorized_keys=0600 --mode /root/.ssh=0700 \
	I915_TEST_VBT=$vbt ZEDBSD_TEST_IMAGE_TAG=demo-hdmi "$@"
echo "demo image: $build/hdd-image.img"
